// Copyright 2026 enieuwy. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"os"
	"os/signal"
	"syscall"

	"github.com/mark3labs/mcp-go/server"
	mcptools "zotero-pp-cli/internal/mcp"
)

func main() {
	// PATCH(glean qfuq): advertise resource + prompt capabilities alongside
	// tools so hosts can discover Zotero context and guided workflows.
	s := server.NewMCPServer(
		"Zotero",
		"1.0.0",
		server.WithToolCapabilities(false),
		server.WithResourceCapabilities(false, true),
		server.WithPromptCapabilities(true),
	)

	mcptools.RegisterTools(s)
	// PATCH(glean qfuq): first-class MCP resources and prompts.
	mcptools.RegisterResources(s)
	mcptools.RegisterPrompts(s)

	// PATCH(glean roadmap-phase7 3df91067): announce the env-selected library and
	// profile so MCP installs (which configure these via env, not flags) are
	// verifiable from the host's server log.
	if g := os.Getenv("ZOTERO_GROUP"); g != "" {
		fmt.Fprintf(os.Stderr, "Zotero MCP: group library %s\n", g)
	} else {
		fmt.Fprintln(os.Stderr, "Zotero MCP: personal library")
	}
	if p := os.Getenv("ZOTERO_PROFILE"); p != "" {
		fmt.Fprintf(os.Stderr, "Zotero MCP: profile %s\n", p)
	}

	stdout := os.Stdout
	// PATCH(glean field-mcp-transport): stdio MCP uses stdout as the JSON-RPC
	// transport. Mirrored Cobra commands still contain legacy direct
	// os.Stdout writes, so route accidental process-stdout chatter to stderr
	// and pass the original stdout handle only to the MCP transport.
	os.Stdout = os.Stderr
	stdio := server.NewStdioServer(s)
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	signals := make(chan os.Signal, 1)
	signal.Notify(signals, syscall.SIGTERM, syscall.SIGINT)
	defer signal.Stop(signals)
	go func() {
		<-signals
		cancel()
	}()
	if err := stdio.Listen(ctx, os.Stdin, stdout); err != nil {
		fmt.Fprintf(os.Stderr, "MCP server error: %v\n", err)
		os.Exit(1)
	}
}
