// Copyright 2026 OrgMentem. Licensed under MIT. See LICENSE.
// Deterministic reference-doc generator for the Zensical
// documentation site. Walks the live cobra command tree and the introspection
// exports (capabilities, feature index) plus tools-manifest.json, emitting the
// docs/reference/*.md pages. These pages are code-generated and drift-gated in
// CI (see .github/workflows/ci.yml docs-drift job) so they cannot fall out of
// sync with the binary. Regenerate with `make docs-gen`.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"zotio/internal/cli"
)

const genHeader = "<!-- Code-generated by cmd/docs-gen; DO NOT EDIT. Regenerate with `make docs-gen`. -->\n"

func main() {
	outDir := flag.String("out", filepath.Join("docs", "reference"), "output directory for generated reference pages")
	toolsManifest := flag.String("tools-manifest", "tools-manifest.json", "path to the MCP tools manifest")
	// -llms-out generates agent-facing llms.txt +
	// llms-full.txt into the given dir (the built site) and skips reference
	// regen. Emitted at deploy time (see docs.yml), never committed, so they
	// cannot drift — same lifecycle as the live badge.
	llmsOut := flag.String("llms-out", "", "generate llms.txt + llms-full.txt into this dir (skips reference generation)")
	flag.Parse()

	if *llmsOut != "" {
		if err := generateLLMS("docs", *llmsOut); err != nil {
			fmt.Fprintln(os.Stderr, "docs-gen:", err)
			os.Exit(1)
		}
		return
	}
	if err := run(*outDir, *toolsManifest); err != nil {
		fmt.Fprintln(os.Stderr, "docs-gen:", err)
		os.Exit(1)
	}
}

func run(outDir, toolsManifest string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	root := cli.RootCmd()

	writers := map[string]func() ([]byte, error){
		"commands.md":     func() ([]byte, error) { return renderCommands(root), nil },
		"capabilities.md": renderCapabilities,
		"highlights.md":   renderHighlights,
		"mcp-tools.md":    func() ([]byte, error) { return renderMCPTools(toolsManifest) },
	}
	names := make([]string, 0, len(writers))
	for n := range writers {
		names = append(names, n)
	}
	sort.Strings(names)

	for _, name := range names {
		body, err := writers[name]()
		if err != nil {
			return fmt.Errorf("%s: %w", name, err)
		}
		path := filepath.Join(outDir, name)
		if err := os.WriteFile(path, body, 0o600); err != nil {
			return err
		}
		fmt.Println("wrote", path)
	}
	return nil
}

// ---- command reference ----------------------------------------------------

func renderCommands(root *cobra.Command) []byte {
	var b bytes.Buffer
	b.WriteString(genHeader)
	b.WriteString("# Command reference\n\n")
	b.WriteString("Every `zotio` command, generated directly from the binary. Add `--agent` to any command for JSON output and non-interactive defaults; mutating commands preview unless `--yes` is passed.\n\n")

	if gf := flagRows(root.PersistentFlags()); len(gf) > 0 {
		b.WriteString("## Global flags\n\n")
		b.WriteString("These flags are available on every command.\n\n")
		writeFlagTable(&b, gf)
		b.WriteString("\n")
	}

	for _, c := range visibleSubcommands(root) {
		writeCommand(&b, c, 2)
	}
	return b.Bytes()
}

func writeCommand(b *bytes.Buffer, c *cobra.Command, level int) {
	hashes := strings.Repeat("#", level)
	fmt.Fprintf(b, "%s `%s`\n\n", hashes, c.CommandPath())

	if s := strings.TrimSpace(c.Short); s != "" {
		fmt.Fprintf(b, "%s\n\n", s)
	}
	if long := strings.TrimSpace(c.Long); long != "" && long != strings.TrimSpace(c.Short) {
		fmt.Fprintf(b, "%s\n\n", long)
	}

	fmt.Fprintf(b, "```\n%s\n```\n\n", strings.TrimSpace(c.UseLine()))

	if ex := strings.TrimSpace(c.Example); ex != "" {
		b.WriteString("Examples:\n\n")
		fmt.Fprintf(b, "```bash\n%s\n```\n\n", ex)
	}

	if rows := flagRows(c.NonInheritedFlags()); len(rows) > 0 {
		writeFlagTable(b, rows)
		b.WriteString("\n")
	}

	for _, sub := range visibleSubcommands(c) {
		writeCommand(b, sub, min(level+1, 6))
	}
}

func visibleSubcommands(c *cobra.Command) []*cobra.Command {
	var out []*cobra.Command
	for _, sub := range c.Commands() {
		if sub.Hidden || !sub.IsAvailableCommand() {
			continue
		}
		switch sub.Name() {
		case "help", "completion":
			continue
		}
		out = append(out, sub)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name() < out[j].Name() })
	return out
}

type flagRow struct{ name, typ, def, usage string }

func flagRows(fs *pflag.FlagSet) []flagRow {
	var rows []flagRow
	fs.VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		name := "--" + f.Name
		if f.Shorthand != "" {
			name = "-" + f.Shorthand + ", " + name
		}
		rows = append(rows, flagRow{
			name:  name,
			typ:   f.Value.Type(),
			def:   f.DefValue,
			usage: strings.ReplaceAll(f.Usage, "|", "\\|"),
		})
	})
	sort.Slice(rows, func(i, j int) bool { return rows[i].name < rows[j].name })
	return rows
}

func writeFlagTable(b *bytes.Buffer, rows []flagRow) {
	b.WriteString("| Flag | Type | Default | Description |\n")
	b.WriteString("| --- | --- | --- | --- |\n")
	for _, r := range rows {
		def := r.def
		if def != "" {
			def = "`" + def + "`"
		}
		fmt.Fprintf(b, "| `%s` | `%s` | %s | %s |\n", r.name, r.typ, def, r.usage)
	}
}

// ---- capabilities ---------------------------------------------------------

type capEntry struct {
	Path        string   `json:"path"`
	Operation   string   `json:"operation"`
	DataSources []string `json:"data_sources,omitempty"`
	WriteTarget string   `json:"write_target,omitempty"`
	Destructive bool     `json:"destructive,omitempty"`
	Requires    []string `json:"requires,omitempty"`
}

func renderCapabilities() ([]byte, error) {
	raw, err := cli.CapabilitiesJSON()
	if err != nil {
		return nil, err
	}
	var entries []capEntry
	if err := json.Unmarshal(raw, &entries); err != nil {
		return nil, err
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Path < entries[j].Path })

	b := &bytes.Buffer{}
	b.WriteString(genHeader)
	b.WriteString("# Capabilities & trust model\n\n")
	b.WriteString("The machine-readable registry every command is classified against — read vs. write, where writes land, whether they are destructive, and what they require. Emit it live with `zotio capabilities` or over MCP as `zotero://capabilities`.\n\n")
	b.WriteString("| Command | Operation | Write target | Destructive | Requires |\n")
	b.WriteString("| --- | --- | --- | --- | --- |\n")
	for _, e := range entries {
		destructive := ""
		if e.Destructive {
			destructive = "yes"
		}
		fmt.Fprintf(b, "| `%s` | %s | %s | %s | %s |\n",
			e.Path, e.Operation, code(e.WriteTarget), destructive, codeList(e.Requires))
	}
	return b.Bytes(), nil
}

// ---- highlights (feature index) -------------------------------------------

type featureEntry struct {
	Command      string `json:"command"`
	Description  string `json:"description"`
	Group        string `json:"group,omitempty"`
	WhyItMatters string `json:"why_it_matters,omitempty"`
}

func renderHighlights() ([]byte, error) {
	raw, err := cli.FeatureIndexJSON()
	if err != nil {
		return nil, err
	}
	var entries []featureEntry
	if err := json.Unmarshal(raw, &entries); err != nil {
		return nil, err
	}

	groups := map[string][]featureEntry{}
	var order []string
	for _, e := range entries {
		g := e.Group
		if g == "" {
			g = "Other"
		}
		if _, seen := groups[g]; !seen {
			order = append(order, g)
		}
		groups[g] = append(groups[g], e)
	}
	// Groups render in index declaration order so the
	// flagship pillar leads the page; alphabetical buried it under "Agent & ...".

	b := &bytes.Buffer{}
	b.WriteString(genHeader)
	b.WriteString("# Highlights\n\n")
	b.WriteString("The curated capabilities `zotio` advertises as its hero features — the same index `zotio which \"<goal>\"` resolves natural-language queries against.\n\n")
	for _, g := range order {
		fmt.Fprintf(b, "## %s\n\n", g)
		for _, e := range groups[g] {
			fmt.Fprintf(b, "### `%s`\n\n", e.Command)
			fmt.Fprintf(b, "%s\n\n", e.Description)
			if e.WhyItMatters != "" {
				fmt.Fprintf(b, "> **Why it matters** — %s\n\n", e.WhyItMatters)
			}
		}
	}
	return b.Bytes(), nil
}

// ---- MCP tools ------------------------------------------------------------

type toolsManifestFile struct {
	APIName     string `json:"api_name"`
	Description string `json:"description"`
	MCPReady    string `json:"mcp_ready"`
	Auth        struct {
		Type   string `json:"type"`
		Header string `json:"header"`
	} `json:"auth"`
	Tools []struct {
		Name        string `json:"name"`
		Description string `json:"description"`
	} `json:"tools"`
}

func renderMCPTools(path string) ([]byte, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var m toolsManifestFile
	if err := json.Unmarshal(raw, &m); err != nil {
		return nil, err
	}
	tools := m.Tools
	sort.Slice(tools, func(i, j int) bool { return tools[i].Name < tools[j].Name })

	b := &bytes.Buffer{}
	b.WriteString(genHeader)
	b.WriteString("# MCP tools\n\n")
	if d := strings.TrimSpace(m.Description); d != "" {
		fmt.Fprintf(b, "%s\n\n", d)
	}
	b.WriteString("The default MCP surface is a command-orchestration facade (`command_search` / `command_run`) — see [the MCP server guide](../guide/mcp-server.md). The full one-tool-per-endpoint mirror below is available via `ZOTIO_MCP_SURFACE`.\n\n")
	if m.Auth.Type != "" {
		fmt.Fprintf(b, "**Auth:** `%s`", m.Auth.Type)
		if m.Auth.Header != "" {
			fmt.Fprintf(b, " (header `%s`)", m.Auth.Header)
		}
		b.WriteString("\n\n")
	}
	fmt.Fprintf(b, "| Tool | Description |\n| --- | --- |\n")
	for _, t := range tools {
		fmt.Fprintf(b, "| `%s` | %s |\n", t.Name, strings.ReplaceAll(t.Description, "|", "\\|"))
	}
	return b.Bytes(), nil
}

// ---- helpers --------------------------------------------------------------

func code(s string) string {
	if s == "" {
		return ""
	}
	return "`" + s + "`"
}

func codeList(items []string) string {
	if len(items) == 0 {
		return ""
	}
	out := make([]string, len(items))
	for i, s := range items {
		out[i] = "`" + s + "`"
	}
	return strings.Join(out, ", ")
}

// ---- agent-facing llms.txt / llms-full.txt --------------------------------
// The docs site serves only HTML, which is poor input
// for agents (ZAP-009). We emit two artifacts at the site root: llms.txt (a
// curated index that points agents at the SKILL + CLI first — the
// token-efficient path — then links the pages) and llms-full.txt (the whole
// docs as one clean-Markdown fetch, no HTML scraping). Generated at deploy
// time from the same Markdown sources, so they never drift.

const llmsSiteURL = "https://orgmentem.github.io/zotio/"

var llmsSectionRank = map[string]int{"guide": 1, "concepts": 2, "reference": 3, "contributing": 4}

var llmsCommentRE = regexp.MustCompile(`(?s)<!--.*?-->\n?`)

type llmsPage struct {
	rel   string // e.g. "guide/install" ("index" for the landing page)
	url   string
	title string
	desc  string
	body  string // cleaned Markdown
}

func generateLLMS(srcDir, outDir string) error {
	var paths []string
	err := filepath.WalkDir(srcDir, func(p string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() && strings.HasSuffix(p, ".md") {
			paths = append(paths, p)
		}
		return nil
	})
	if err != nil {
		return err
	}

	pages := make([]llmsPage, 0, len(paths))
	for _, p := range paths {
		raw, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		body := strings.TrimSpace(llmsCommentRE.ReplaceAllString(string(raw), ""))
		rel := strings.TrimSuffix(strings.TrimPrefix(filepath.ToSlash(p), filepath.ToSlash(srcDir)+"/"), ".md")
		url := llmsSiteURL
		if rel != "index" {
			url += rel + "/"
		}
		pages = append(pages, llmsPage{rel: rel, url: url, title: llmsTitle(body, rel), desc: llmsDesc(body), body: body})
	}

	sort.SliceStable(pages, func(i, j int) bool {
		ri, rj := llmsRank(pages[i].rel), llmsRank(pages[j].rel)
		if ri != rj {
			return ri < rj
		}
		return pages[i].rel < pages[j].rel
	})

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(outDir, "llms.txt"), []byte(renderLLMSIndex(pages)), 0o600); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(outDir, "llms-full.txt"), []byte(renderLLMSFull(pages)), 0o600); err != nil {
		return err
	}
	fmt.Println("wrote", filepath.Join(outDir, "llms.txt"), "and llms-full.txt")
	return nil
}

func llmsRank(rel string) int {
	if rel == "index" {
		return 0
	}
	if i := strings.IndexByte(rel, '/'); i >= 0 {
		if r, ok := llmsSectionRank[rel[:i]]; ok {
			return r
		}
	}
	return 5
}

func llmsSection(rel string) string {
	if i := strings.IndexByte(rel, '/'); i >= 0 {
		s := rel[:i]
		return strings.ToUpper(s[:1]) + s[1:]
	}
	return "Overview"
}

func llmsTitle(body, rel string) string {
	for _, line := range strings.Split(body, "\n") {
		if strings.HasPrefix(line, "# ") {
			return strings.TrimSpace(line[2:])
		}
	}
	return rel
}

func llmsDesc(body string) string {
	for _, line := range strings.Split(body, "\n") {
		t := strings.TrimSpace(line)
		if t == "" || strings.HasPrefix(t, "#") || strings.HasPrefix(t, "<") || strings.HasPrefix(t, "!") {
			continue
		}
		// Collapse trivial markdown emphasis/links to plain-ish text.
		t = strings.NewReplacer("**", "", "`", "").Replace(t)
		if len(t) > 200 {
			t = t[:197] + "..."
		}
		return t
	}
	return ""
}

func renderLLMSIndex(pages []llmsPage) string {
	var b strings.Builder
	b.WriteString("# zotio\n\n")
	b.WriteString("> The trust-and-automation layer for Zotero — local-first search, library health, preview-first writes, annotation export, and an MCP server, in the terminal.\n\n")
	b.WriteString("For AI agents: the most token-efficient way to use zotio is NOT scraping these HTML docs. Prefer, in order:\n")
	b.WriteString("1. The bundled agent skill — https://raw.githubusercontent.com/OrgMentem/zotio/main/SKILL.md\n")
	b.WriteString("2. The local CLI: `zotio which \"<goal>\"` resolves a goal to a command; add `--agent` for JSON; `zotio agent-context` and `zotio capabilities` describe the surface.\n")
	b.WriteString("3. The MCP server `zotio-mcp` (bundled with the CLI) for MCP hosts.\n\n")
	b.WriteString("The complete documentation as one Markdown file: " + llmsSiteURL + "llms-full.txt\n\n")

	section := ""
	for _, p := range pages {
		s := llmsSection(p.rel)
		if s != section {
			section = s
			b.WriteString("\n## " + section + "\n\n")
		}
		b.WriteString("- [" + p.title + "](" + p.url + ")")
		if p.desc != "" {
			b.WriteString(": " + p.desc)
		}
		b.WriteString("\n")
	}
	return b.String()
}

func renderLLMSFull(pages []llmsPage) string {
	var b strings.Builder
	b.WriteString("# zotio — full documentation\n\n")
	b.WriteString("The trust-and-automation layer for Zotero. This file concatenates the complete docs as Markdown for AI agents. Source: " + llmsSiteURL + "\n")
	b.WriteString("For the token-efficient path, prefer the bundled SKILL.md and the local CLI (`zotio which`, `--agent`) over consuming this whole file.\n")
	for _, p := range pages {
		b.WriteString("\n\n---\n\n> Source: " + p.url + "\n\n")
		b.WriteString(p.body)
		b.WriteString("\n")
	}
	return b.String()
}
