# Container image for zotio-mcp, the Zotero MCP server (stdio transport).
# Used by Glama to build, security-scan, introspect tools, and let users deploy.
# Tool listing needs no ZOTERO_API_KEY (reads are keyless; the key only unlocks
# writes and group libraries), so introspection works out of the box.
FROM golang:1.26-alpine@sha256:28d89ee9cc0ff9fec75c82ca201e6bf7fdf9a679d4b7b24dfa04f2bb766bb468 AS build
ARG VERSION=dev
WORKDIR /src
# Cache module downloads independently of source changes.
COPY go.mod go.sum ./
RUN go mod download
COPY . .
# Static binary (matches the release build): no libc, runs on distroless/static.
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w -X zotio/internal/cli.version=${VERSION}" -o /out/zotio-mcp ./cmd/zotio-mcp

FROM gcr.io/distroless/static-debian12:nonroot@sha256:afa5c872c891853ca7fcf1f12c3edb23f7eeef36189728842dd51042ff57f7ab
COPY --from=build /out/zotio-mcp /usr/local/bin/zotio-mcp
# The binary is static and links BSD-3-Clause and Apache-2.0 code, so the
# notices travel with it. Generated by `make notices`.
COPY --from=build /src/LICENSE /src/THIRD_PARTY_LICENSES.txt /usr/local/share/doc/zotio/
# Default transport is stdio — the channel Glama (and Claude Desktop) speak.
ENTRYPOINT ["/usr/local/bin/zotio-mcp"]
