// Copyright 2026 enieuwy. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"zotero-pp-cli/internal/cli"
	"zotero-pp-cli/internal/client"
	"zotero-pp-cli/internal/cliutil"
	"zotero-pp-cli/internal/config"
	"zotero-pp-cli/internal/mcp/cobratree"
	"zotero-pp-cli/internal/store"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("collections_create",
			mcplib.WithDescription("Create one or more collections. Required: name. Optional: parentCollection. (requires API key)"),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("Collection name")),
			mcplib.WithString("parentCollection", mcplib.Description("Parent collection key (omit for top-level)")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/collections", []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "body"}, {PublicName: "parentCollection", WireName: "parentCollection", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("collections_delete",
			mcplib.WithDescription("Delete a collection (does not delete items). Required: collectionKey. Destructive. (requires API key)"),
			mcplib.WithString("collectionKey", mcplib.Required(), mcplib.Description("Collection key to delete")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/collections/{collectionKey}", []mcpParamBinding{{PublicName: "collectionKey", WireName: "collectionKey", Location: "path"}}, []string{"collectionKey"}),
	)
	s.AddTool(
		mcplib.NewTool("collections_get",
			mcplib.WithDescription("Get a specific collection. Required: collectionKey. Returns the Collection."),
			mcplib.WithString("collectionKey", mcplib.Required(), mcplib.Description("Collection key (e.g. IDTUAULN)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/collections/{collectionKey}", []mcpParamBinding{{PublicName: "collectionKey", WireName: "collectionKey", Location: "path"}}, []string{"collectionKey"}),
	)
	s.AddTool(
		mcplib.NewTool("collections_items",
			mcplib.WithDescription("List all items in a collection. Required: collectionKey. Optional: limit, start, format. Returns array of Item."),
			mcplib.WithString("collectionKey", mcplib.Required(), mcplib.Description("Collection key")),
			mcplib.WithString("limit", mcplib.Description("Maximum number of items to return")),
			mcplib.WithString("start", mcplib.Description("Pagination offset")),
			mcplib.WithString("format", mcplib.Description("Response format (json, bibtex, ris, etc.)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/collections/{collectionKey}/items", []mcpParamBinding{{PublicName: "collectionKey", WireName: "collectionKey", Location: "path"}, {PublicName: "limit", WireName: "limit", Location: "query"}, {PublicName: "start", WireName: "start", Location: "query"}, {PublicName: "format", WireName: "format", Location: "query"}}, []string{"collectionKey"}),
	)
	s.AddTool(
		mcplib.NewTool("collections_list",
			mcplib.WithDescription("List all collections. Optional: limit, start. Returns array of Collection."),
			mcplib.WithString("limit", mcplib.Description("Maximum number of collections to return")),
			mcplib.WithString("start", mcplib.Description("Pagination offset")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/collections", []mcpParamBinding{{PublicName: "limit", WireName: "limit", Location: "query"}, {PublicName: "start", WireName: "start", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("collections_subcollections",
			mcplib.WithDescription("List subcollections of a collection. Required: collectionKey. Returns array of Collection."),
			mcplib.WithString("collectionKey", mcplib.Required(), mcplib.Description("Collection key")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/collections/{collectionKey}/collections", []mcpParamBinding{{PublicName: "collectionKey", WireName: "collectionKey", Location: "path"}}, []string{"collectionKey"}),
	)
	s.AddTool(
		mcplib.NewTool("collections_tags",
			mcplib.WithDescription("List tags used within a collection. Required: collectionKey. Returns array of Tag."),
			mcplib.WithString("collectionKey", mcplib.Required(), mcplib.Description("Collection key")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/collections/{collectionKey}/tags", []mcpParamBinding{{PublicName: "collectionKey", WireName: "collectionKey", Location: "path"}}, []string{"collectionKey"}),
	)
	s.AddTool(
		mcplib.NewTool("collections_top",
			mcplib.WithDescription("List only top-level collections (no parents). Optional: limit. Returns array of Collection."),
			mcplib.WithString("limit", mcplib.Description("Maximum number to return")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/collections/top", []mcpParamBinding{{PublicName: "limit", WireName: "limit", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("collections_update",
			mcplib.WithDescription("Update a collection. Required: collectionKey. Optional: name, parentCollection. (requires API key)"),
			mcplib.WithString("collectionKey", mcplib.Required(), mcplib.Description("Collection key to update")),
			mcplib.WithString("name", mcplib.Description("New collection name")),
			mcplib.WithString("parentCollection", mcplib.Description("New parent collection key (false for top-level)")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/collections/{collectionKey}", []mcpParamBinding{{PublicName: "collectionKey", WireName: "collectionKey", Location: "path"}, {PublicName: "name", WireName: "name", Location: "body"}, {PublicName: "parentCollection", WireName: "parentCollection", Location: "body"}}, []string{"collectionKey"}),
	)
	s.AddTool(
		mcplib.NewTool("items_children",
			mcplib.WithDescription("Get child items (attachments and notes) for an item. Required: itemKey. Optional: itemType. Returns array of Item."),
			mcplib.WithString("itemKey", mcplib.Required(), mcplib.Description("Parent item key")),
			mcplib.WithString("itemType", mcplib.Description("Filter by type (attachment or note)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/items/{itemKey}/children", []mcpParamBinding{{PublicName: "itemKey", WireName: "itemKey", Location: "path"}, {PublicName: "itemType", WireName: "itemType", Location: "query"}}, []string{"itemKey"}),
	)
	s.AddTool(
		mcplib.NewTool("items_create",
			mcplib.WithDescription("Create one or more items. Optional: items. (requires API key)"),
			mcplib.WithString("items", mcplib.Description("Array of item objects to create (use item-types and item-type-fields for schema)")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/items", []mcpParamBinding{{PublicName: "items", WireName: "items", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("items_delete",
			mcplib.WithDescription("Delete an item (moves to trash). Required: itemKey. Destructive. (requires API key)"),
			mcplib.WithString("itemKey", mcplib.Required(), mcplib.Description("Item key to delete")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/items/{itemKey}", []mcpParamBinding{{PublicName: "itemKey", WireName: "itemKey", Location: "path"}}, []string{"itemKey"}),
	)
	s.AddTool(
		mcplib.NewTool("items_get",
			mcplib.WithDescription("Get a single item by key. Required: itemKey. Optional: format. Returns the Item."),
			mcplib.WithString("itemKey", mcplib.Required(), mcplib.Description("Zotero item key (e.g. 9UXV5R7L)")),
			mcplib.WithString("format", mcplib.Description("Response format (json, bib, bibtex, csljson, ris, etc.)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/items/{itemKey}", []mcpParamBinding{{PublicName: "itemKey", WireName: "itemKey", Location: "path"}, {PublicName: "format", WireName: "format", Location: "query"}}, []string{"itemKey"}),
	)
	s.AddTool(
		mcplib.NewTool("items_list",
			mcplib.WithDescription("List all items in the library. Optional: limit, start, sort (plus 6 more). Returns array of Item."),
			mcplib.WithString("limit", mcplib.Description("Maximum number of items to return (max 100)")),
			mcplib.WithString("start", mcplib.Description("Pagination offset (zero-based)")),
			mcplib.WithString("sort", mcplib.Description("Sort field (dateAdded, dateModified, title, creator, type, date, publisher, publicationTitle, journalAbbreviation,...")),
			mcplib.WithString("direction", mcplib.Description("Sort direction (asc or desc)")),
			mcplib.WithString("itemType", mcplib.Description("Filter by item type (journalArticle, book, bookSection, conferencePaper, etc.)")),
			mcplib.WithString("query", mcplib.Description("Quick search across title, creator, and year")),
			mcplib.WithString("tag", mcplib.Description("Filter by tag name")),
			mcplib.WithString("since", mcplib.Description("Return only items modified after this library version number")),
			mcplib.WithString("format", mcplib.Description("Response format (json, atom, bib, bibtex, bookmarks, coins, csljson, mods, refer, rdf_bibliontology, rdf_dc,...")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/items", []mcpParamBinding{{PublicName: "limit", WireName: "limit", Location: "query"}, {PublicName: "start", WireName: "start", Location: "query"}, {PublicName: "sort", WireName: "sort", Location: "query"}, {PublicName: "direction", WireName: "direction", Location: "query"}, {PublicName: "itemType", WireName: "itemType", Location: "query"}, {PublicName: "query", WireName: "q", Location: "query"}, {PublicName: "tag", WireName: "tag", Location: "query"}, {PublicName: "since", WireName: "since", Location: "query"}, {PublicName: "format", WireName: "format", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("items_tags",
			mcplib.WithDescription("Get tags for a specific item. Required: itemKey. Returns array of Tag."),
			mcplib.WithString("itemKey", mcplib.Required(), mcplib.Description("Item key")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/items/{itemKey}/tags", []mcpParamBinding{{PublicName: "itemKey", WireName: "itemKey", Location: "path"}}, []string{"itemKey"}),
	)
	s.AddTool(
		mcplib.NewTool("items_top",
			mcplib.WithDescription("List top-level items only (excludes attachments and notes). Optional: limit, start, sort (plus 3 more). Returns array of Item."),
			mcplib.WithString("limit", mcplib.Description("Maximum number of items to return")),
			mcplib.WithString("start", mcplib.Description("Pagination offset")),
			mcplib.WithString("sort", mcplib.Description("Sort field")),
			mcplib.WithString("tag", mcplib.Description("Filter by tag")),
			mcplib.WithString("itemType", mcplib.Description("Filter by item type")),
			mcplib.WithString("query", mcplib.Description("Quick search query")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/items/top", []mcpParamBinding{{PublicName: "limit", WireName: "limit", Location: "query"}, {PublicName: "start", WireName: "start", Location: "query"}, {PublicName: "sort", WireName: "sort", Location: "query"}, {PublicName: "tag", WireName: "tag", Location: "query"}, {PublicName: "itemType", WireName: "itemType", Location: "query"}, {PublicName: "query", WireName: "q", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("items_trash",
			mcplib.WithDescription("List items in the trash. Optional: limit. Returns array of Item."),
			mcplib.WithString("limit", mcplib.Description("Maximum number of items to return")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/items/trash", []mcpParamBinding{{PublicName: "limit", WireName: "limit", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("items_update",
			mcplib.WithDescription("Update a specific item. Required: itemKey. Optional: title, abstractNote, tags (plus 2 more). Partial update. (requires API key)"),
			mcplib.WithString("itemKey", mcplib.Required(), mcplib.Description("Item key to update")),
			mcplib.WithString("title", mcplib.Description("Item title")),
			mcplib.WithString("abstractNote", mcplib.Description("Abstract or summary")),
			mcplib.WithString("tags", mcplib.Description("Tags to apply (array of {tag: string} objects)")),
			mcplib.WithString("collections", mcplib.Description("Collection keys to assign this item to")),
			mcplib.WithString("extra", mcplib.Description("Extra notes field (also stores Better BibTeX citation key)")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PATCH", "/items/{itemKey}", []mcpParamBinding{{PublicName: "itemKey", WireName: "itemKey", Location: "path"}, {PublicName: "title", WireName: "title", Location: "body"}, {PublicName: "abstractNote", WireName: "abstractNote", Location: "body"}, {PublicName: "tags", WireName: "tags", Location: "body"}, {PublicName: "collections", WireName: "collections", Location: "body"}, {PublicName: "extra", WireName: "extra", Location: "body"}}, []string{"itemKey"}),
	)
	s.AddTool(
		mcplib.NewTool("schema_creator-fields",
			mcplib.WithDescription("List all creator fields (firstName, lastName, name). Returns array of CreatorField."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/creatorFields", []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("schema_item-fields",
			mcplib.WithDescription("List all available item fields. Returns array of ItemField."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/itemFields", []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("schema_item-type-creator-types",
			mcplib.WithDescription("List valid creator types for an item type. Required: itemType. Returns array of CreatorType."),
			mcplib.WithString("itemType", mcplib.Required(), mcplib.Description("Item type (e.g. journalArticle)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/itemTypeCreatorTypes", []mcpParamBinding{{PublicName: "itemType", WireName: "itemType", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("schema_item-type-fields",
			mcplib.WithDescription("List valid fields for a specific item type. Required: itemType. Returns array of ItemField."),
			mcplib.WithString("itemType", mcplib.Required(), mcplib.Description("Item type (e.g. journalArticle)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/itemTypeFields", []mcpParamBinding{{PublicName: "itemType", WireName: "itemType", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("schema_item-types",
			mcplib.WithDescription("List all available Zotero item types. Returns array of ItemType."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/itemTypes", []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("schema_new-item-template",
			mcplib.WithDescription("Get a blank template for creating a new item of a given type. Required: itemType. Returns the Item."),
			mcplib.WithString("itemType", mcplib.Required(), mcplib.Description("Item type to get template for (e.g. journalArticle)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/items/new", []mcpParamBinding{{PublicName: "itemType", WireName: "itemType", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("searches_get",
			mcplib.WithDescription("Get a specific saved search. Required: searchKey. Returns the Search."),
			mcplib.WithString("searchKey", mcplib.Required(), mcplib.Description("Search key")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/searches/{searchKey}", []mcpParamBinding{{PublicName: "searchKey", WireName: "searchKey", Location: "path"}}, []string{"searchKey"}),
	)
	s.AddTool(
		mcplib.NewTool("searches_list",
			mcplib.WithDescription("List all saved searches. Optional: limit. Returns array of Search."),
			mcplib.WithString("limit", mcplib.Description("Maximum number of searches to return")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/searches", []mcpParamBinding{{PublicName: "limit", WireName: "limit", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("tags_get",
			mcplib.WithDescription("Get a specific tag by name. Required: tagName. Returns array of Tag."),
			mcplib.WithString("tagName", mcplib.Required(), mcplib.Description("Tag name (URL-encoded)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/tags/{tagName}", []mcpParamBinding{{PublicName: "tagName", WireName: "tagName", Location: "path"}}, []string{"tagName"}),
	)
	s.AddTool(
		mcplib.NewTool("tags_list",
			mcplib.WithDescription("List all tags in the library. Optional: limit, start, query. Returns array of Tag."),
			mcplib.WithString("limit", mcplib.Description("Maximum number of tags to return")),
			mcplib.WithString("start", mcplib.Description("Pagination offset")),
			mcplib.WithString("query", mcplib.Description("Filter tags by name substring")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/tags", []mcpParamBinding{{PublicName: "limit", WireName: "limit", Location: "query"}, {PublicName: "start", WireName: "start", Location: "query"}, {PublicName: "query", WireName: "q", Location: "query"}}, []string{}),
	)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	// PATCH(glean c4ke): pass the RootCmd factory so each mirrored tool runs
	// in-process against a fresh command tree instead of shelling out.
	cobratree.RegisterAll(s, cli.RootCmd)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// PATCH(glean 1b05b22e): percent-encode user-supplied path parameters before
// splicing them into the API path. Raw substitution let a value containing "/"
// (a malicious key in a shared/group library, or a prompt-injected agent)
// re-target a different endpoint: /collections/{k} with k="ABC/items" became
// /collections/ABC/items. url.PathEscape leaves valid Zotero keys ([A-Z0-9]{8})
// untouched. This belongs upstream in the cli-printing-press makeAPIHandler too.
func mcpPathValue(v any) string {
	return url.PathEscape(fmt.Sprintf("%v", v))
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, mcpPathValue(v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, mcpPathValue(v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			data, err = c.Get(path, params)
		case "POST":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Post(path, body)
		case "PUT":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Put(path, body)
		case "PATCH":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Patch(path, body)
		case "DELETE":
			data, _, err = c.Delete(path)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			// PATCH(glean static-audit): classify via the shared cliutil helper
			// so HTTP-status detection isn't duplicated with the CLI layer; the
			// MCP result text stays MCP-specific.
			switch cliutil.ClassifyHTTPError(msg) {
			case cliutil.HTTPErrConflict:
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case cliutil.HTTPErrBadRequestAuth:
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export ZOTERO_API_KEY=<your-key>" +
					"\n      Run 'zotero-pp-cli doctor' to check auth status."), nil
			case cliutil.HTTPErrUnauthorized:
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your API key." +
					"\n      Set it with: export ZOTERO_API_KEY=<your-key>" +
					"\n      Run 'zotero-pp-cli doctor' to check auth status."), nil
			case cliutil.HTTPErrForbidden:
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export ZOTERO_API_KEY=<your-key>" +
					"\n      Run 'zotero-pp-cli doctor' to check auth status."), nil
			case cliutil.HTTPErrNotFound:
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case cliutil.HTTPErrRateLimited:
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "zotero-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "zotero-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" — TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	// PATCH(glean qfuq): single source of truth shared with the
	// zotero://context MCP resource (see resources.go domainContext).
	data, _ := json.MarshalIndent(domainContext(), "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
