// Copyright 2026 OrgMentem. Licensed under MIT. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"path/filepath"
	"strings"
	"testing"
)

// TestValidateReadOnlyQuery_AllowsSelectAndWITH pins the contract: the MCP
// sql tool's allowlist accepts SELECT and WITH-prefix queries, including
// CTEs, mixed case, leading whitespace, leading SQL comments, and leading
// statement separators. SELECT-form CTEs ("WITH x AS (SELECT ...) SELECT")
// must work because novel CLI sql commands in the public library accept
// them as legitimate read-only queries; the MCP surface keeps parity.
func TestValidateReadOnlyQuery_AllowsSelectAndWITH(t *testing.T) {
	allowed := []string{
		"SELECT 1",
		"select * from resources",
		"  SELECT 1",
		"\tSELECT 1",
		"\nSELECT 1",
		";SELECT 1",
		"-- comment\nSELECT 1",
		"/* comment */ SELECT 1",
		"/* comment */SELECT 1",
		"/**/SELECT 1",
		"-- one\n-- two\nSELECT 1",
		"/* a *//* b */ SELECT 1",
		"WITH r AS (SELECT 1) SELECT * FROM r",
		"with r as (select 1) select * from r",
	}
	for _, q := range allowed {
		if err := validateReadOnlyQuery(q); err != nil {
			t.Errorf("validateReadOnlyQuery(%q) = %v, want nil", q, err)
		}
	}
}

// TestValidateReadOnlyQuery_RejectsBypassVectors covers the comment-prefix
// bypass class that defeated the earlier prefix-blocklist gate. mode=ro on
// modernc.org/sqlite does not block VACUUM INTO (writes a fresh file) or
// ATTACH DATABASE (opens a separate writable handle), so the gate is the
// only defense against those vectors. A successful bypass at this layer
// would let an MCP-trusting agent silently exfiltrate the local database.
func TestValidateReadOnlyQuery_RejectsBypassVectors(t *testing.T) {
	rejected := []string{
		"VACUUM INTO '/tmp/x.db'",
		"ATTACH DATABASE 'file:/tmp/x.db?mode=rwc' AS evil",
		"INSERT INTO resources VALUES ('x', 'y', '{}')",
		"UPDATE resources SET resource_type = 'evil'",
		"DELETE FROM resources",
		"REPLACE INTO resources VALUES ('seed', 'evil', '{}')",
		"DROP TABLE resources",
		"PRAGMA writable_schema = ON",
		"REINDEX",
		"DETACH DATABASE x",
		"/* x */ VACUUM INTO '/tmp/exfil.db'",
		"/* x */VACUUM INTO '/tmp/exfil.db'",
		"-- x\nVACUUM INTO '/tmp/exfil.db'",
		"/**/VACUUM INTO '/tmp/exfil.db'",
		"/* x */ ATTACH DATABASE 'file:/tmp/x.db?mode=rwc' AS evil",
		"-- x\nATTACH DATABASE '/tmp/x.db' AS evil",
		";VACUUM INTO '/tmp/x.db'",
		"; ; VACUUM INTO '/tmp/x.db'",
		"/* a */ /* b */ INSERT INTO t VALUES (1)",
		"/* outer /* not nested */ */ SELECT 1", // SQLite doesn't nest, so trailing "*/" closes; second SELECT remains. Reject — the gate must err on the side of caution when the leading shape is suspicious.
		"-- only a comment",
		"/* only a comment */",
		"",
		"   ",
		";",
	}
	for _, q := range rejected {
		if err := validateReadOnlyQuery(q); err == nil {
			t.Errorf("validateReadOnlyQuery(%q) = nil, want error", q)
		}
	}
}

// TestValidateReadOnlyQueryRejectsStackedStatements pins the single-statement
// boundary: a SELECT/WITH prefix is still read-only only when no second
// executable SQL statement follows a semicolon. Semicolons inside strings and
// comments remain data, not statement separators.
func TestValidateReadOnlyQueryRejectsStackedStatements(t *testing.T) {
	allowed := []string{
		"SELECT ';' AS literal",
		`SELECT "not;separator"`,
		"SELECT 1; -- trailing comment",
		"SELECT 1; /* trailing comment */",
		"WITH r AS (SELECT ';') SELECT * FROM r;",
	}
	for _, q := range allowed {
		if err := validateReadOnlyQuery(q); err != nil {
			t.Errorf("validateReadOnlyQuery(%q) = %v, want nil", q, err)
		}
	}

	rejected := []string{
		"SELECT 1; VACUUM INTO '/tmp/exfil.db'",
		"SELECT 1; ATTACH DATABASE '/tmp/exfil.db' AS exfil",
		"SELECT 1; INSERT INTO resources VALUES ('x', 'items', '{}')",
		"WITH r AS (SELECT 1) SELECT * FROM r; DELETE FROM resources",
		"SELECT ';'; UPDATE resources SET resource_type = 'items'",
		"SELECT 1 /* ; */; DROP TABLE resources",
	}
	for _, q := range rejected {
		if err := validateReadOnlyQuery(q); err == nil {
			t.Errorf("validateReadOnlyQuery(%q) = nil, want stacked-statement error", q)
		}
	}
}

func TestDBPathUsesNumericZoteroGroup(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	t.Setenv("ZOTERO_GROUP", "12345")
	if got, want := dbPath(), filepath.Join(home, ".local", "share", "zotio", "data-group-12345.db"); got != want {
		t.Fatalf("dbPath() with numeric group = %q, want %q", got, want)
	}

	t.Setenv("ZOTERO_GROUP", "team-alpha")
	if got, want := dbPath(), filepath.Join(home, ".local", "share", "zotio", "data.db"); got != want {
		t.Fatalf("dbPath() with non-numeric group = %q, want personal DB %q", got, want)
	}
}

// TestStripLeadingSQLNoise checks the helper directly so a regression in the
// stripping logic (off-by-one on /* */ length, missing newline handling on
// --) surfaces close to the source rather than only via the integration
// behavior of validateReadOnlyQuery.
func TestStripLeadingSQLNoise(t *testing.T) {
	cases := []struct {
		in, want string
	}{
		{"SELECT 1", "SELECT 1"},
		{"  SELECT 1", "SELECT 1"},
		{"\t\nSELECT 1", "SELECT 1"},
		{";SELECT 1", "SELECT 1"},
		{";; ;SELECT 1", "SELECT 1"},
		{"-- x\nSELECT 1", "SELECT 1"},
		{"-- x\n-- y\nSELECT 1", "SELECT 1"},
		{"/* x */SELECT 1", "SELECT 1"},
		{"/**/SELECT 1", "SELECT 1"},
		{"/* x */ /* y */ SELECT 1", "SELECT 1"},
		{"-- only", ""},
		{"/* only", ""},
		{"", ""},
	}
	for _, c := range cases {
		got := stripLeadingSQLNoise(c.in)
		if !strings.EqualFold(got, c.want) {
			t.Errorf("stripLeadingSQLNoise(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}
