// Copyright 2026 enieuwy. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCollectionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "collections",
		Short: "Manage collections in your Zotero library",
	}

	cmd.AddCommand(newCollectionsCreateCmd(flags))
	cmd.AddCommand(newCollectionsDeleteCmd(flags))
	cmd.AddCommand(newCollectionsGetCmd(flags))
	cmd.AddCommand(newCollectionsItemsCmd(flags))
	cmd.AddCommand(newCollectionsListCmd(flags))
	// PATCH: Register hand-written Zotero collection workflows added after generation.
	cmd.AddCommand(newCollectionsExportCmd(flags))
	cmd.AddCommand(newCollectionsMoveCmd(flags))
	cmd.AddCommand(newCollectionsStatsCmd(flags))
	cmd.AddCommand(newCollectionsSubcollectionsCmd(flags))
	cmd.AddCommand(newCollectionsTagsCmd(flags))
	cmd.AddCommand(newCollectionsTopCmd(flags))
	cmd.AddCommand(newCollectionsUpdateCmd(flags))
	return cmd
}
