// Copyright 2026 OrgMentem. Licensed under MIT. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"context"
	"encoding/json"
	"fmt"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
	"time"

	"zotio/internal/client"
	"zotio/internal/store"
)

// isNetworkError returns true for errors caused by network connectivity issues
// (DNS, connection refused, timeout). HTTP 4xx/5xx errors are NOT network errors.
func isNetworkError(err error) bool {
	if err == nil {
		return false
	}
	var urlErr *url.Error
	if As(err, &urlErr) {
		// url.Error wraps the underlying network error
		err = urlErr.Err
	}
	var netErr *net.OpError
	if As(err, &netErr) {
		return true
	}
	var dnsErr *net.DNSError
	if As(err, &dnsErr) {
		return true
	}
	// Check for common network error strings
	msg := err.Error()
	return strings.Contains(msg, "connection refused") ||
		strings.Contains(msg, "no such host") ||
		strings.Contains(msg, "network is unreachable") ||
		strings.Contains(msg, "i/o timeout") ||
		strings.Contains(msg, "TLS handshake timeout")
}

// openStoreForRead opens the local SQLite store for reading.
// Returns nil, nil if the database file does not exist (no sync has been run).
func openStoreForRead(ctx context.Context, cliName string) (*store.Store, error) {
	dbPath := defaultDBPath(cliName)
	if _, err := os.Stat(dbPath); os.IsNotExist(err) {
		return nil, nil
	}
	return store.OpenWithContext(ctx, dbPath)
}

// localProvenance builds a DataProvenance for local data reads.
func localProvenance(db *store.Store, resourceType, reason string) DataProvenance {
	prov := DataProvenance{
		Source:       "local",
		Reason:       reason,
		ResourceType: resourceType,
	}
	_, lastSynced, _, err := db.GetSyncState(resourceType)
	if err == nil && !lastSynced.IsZero() {
		prov.SyncedAt = &lastSynced
	}
	return prov
}

func attachFreshness(prov DataProvenance, flags *rootFlags) DataProvenance {
	if flags != nil {
		prov.Freshness = flags.freshnessMeta
	}
	return prov
}

// isLocalListRead detects generated list commands that still pass isList=false.
// PATCH(glean bugfix): base resource paths ("/collections", "/tags",
// "/searches") contain no concrete item key, so local mode must list rows
// instead of treating the resource name as an ID.
func isLocalListRead(resourceType string, isList bool, path string) bool {
	if isList {
		return true
	}
	return strings.Trim(path, "/") == resourceType
}

// resolveRead dispatches a GET request to either the live API or local store
// based on the --data-source flag. Returns the response data and provenance metadata.
//
// Parameters:
//   - c: the HTTP client for live API calls
//   - flags: root flags containing dataSource setting
//   - resourceType: the store resource type name (e.g., "links", "domains")
//   - isList: true for list endpoints, false for get-by-ID endpoints
//   - path: the API path (e.g., "/links" or "/links/abc123")
//   - params: query parameters for the API call
//   - headers: per-endpoint required headers (e.g. cal-api-version, Stripe-Version)
//     baked in by the command template at codegen time. Pass nil when the endpoint
//     declares no per-endpoint header overrides. Without this parameter, store-backed
//     reads on per-endpoint-versioned APIs silently get the wrong response shape
//     (cal-com retro #334 F1).
func resolveRead(ctx context.Context, c *client.Client, flags *rootFlags, resourceType string, isList bool, path string, params map[string]string, headers map[string]string) (json.RawMessage, DataProvenance, error) {
	switch flags.dataSource {
	case "local":
		data, prov, err := resolveLocal(ctx, resourceType, isList, path, params, "user_requested")
		return data, attachFreshness(prov, flags), err

	case "live":
		data, err := c.GetWithHeaders(path, params, headers)
		if err != nil {
			return nil, DataProvenance{}, err
		}
		return data, attachFreshness(DataProvenance{Source: "live"}, flags), nil

	default: // "auto"
		data, err := c.GetWithHeaders(path, params, headers)
		if err == nil {
			writeThroughCache(ctx, resourceType, data)
			return data, attachFreshness(DataProvenance{Source: "live"}, flags), nil
		}
		if !isNetworkError(err) {
			// HTTP 4xx/5xx errors propagate — not a fallback case
			return nil, DataProvenance{}, err
		}
		// Network error — try local fallback
		fallbackData, fallbackProv, fallbackErr := resolveLocal(ctx, resourceType, isList, path, params, "api_unreachable")
		if fallbackErr != nil {
			return nil, DataProvenance{}, fmt.Errorf("API unreachable and no local data. Run 'zotio sync' to enable offline access.\n\nOriginal error: %w", err)
		}
		return fallbackData, attachFreshness(fallbackProv, flags), nil
	}
}

// resolvePaginatedRead dispatches a paginated GET request to either the live API
// or local store. When local, skips pagination and returns all synced data. The
// headers argument carries per-endpoint required headers; pass nil when the
// endpoint declares no overrides.
func resolvePaginatedRead(ctx context.Context, c *client.Client, flags *rootFlags, resourceType string, path string, params map[string]string, headers map[string]string, fetchAll bool, cursorParam, nextCursorPath, hasMoreField string) (json.RawMessage, DataProvenance, error) {
	switch flags.dataSource {
	case "local":
		data, prov, err := resolveLocal(ctx, resourceType, true, path, params, "user_requested")
		return data, attachFreshness(prov, flags), err

	case "live":
		data, err := paginatedGet(c, path, params, headers, fetchAll, cursorParam, nextCursorPath, hasMoreField)
		if err != nil {
			return nil, DataProvenance{}, err
		}
		return data, attachFreshness(DataProvenance{Source: "live"}, flags), nil

	default: // "auto"
		data, err := paginatedGet(c, path, params, headers, fetchAll, cursorParam, nextCursorPath, hasMoreField)
		if err == nil {
			writeThroughCache(ctx, resourceType, data)
			return data, attachFreshness(DataProvenance{Source: "live"}, flags), nil
		}
		if !isNetworkError(err) {
			return nil, DataProvenance{}, err
		}
		fallbackData, fallbackProv, fallbackErr := resolveLocal(ctx, resourceType, true, path, params, "api_unreachable")
		if fallbackErr != nil {
			return nil, DataProvenance{}, fmt.Errorf("API unreachable and no local data. Run 'zotio sync' to enable offline access.\n\nOriginal error: %w", err)
		}
		return fallbackData, attachFreshness(fallbackProv, flags), nil
	}
}

// writeThroughCache upserts live API results into the local SQLite store so
// FTS search covers everything the user has looked up — not just explicit syncs.
// Best-effort: failures are silently ignored (the live result already succeeded).
func writeThroughCache(ctx context.Context, resourceType string, data json.RawMessage) {
	// PATCH: schema/type lists (itemTypes, itemFields, …) are not keyed library
	// items; write-through caching them only triggers "no extractable ID" warnings
	// from UpsertBatch. They are read-only reference data, so skip the cache.
	if resourceType == "schema" {
		return
	}
	db, err := store.OpenWithContext(ctx, defaultDBPath("zotio"))
	if err != nil {
		return
	}
	defer db.Close()

	// Collect items to upsert from various response shapes
	var items []json.RawMessage

	// Try direct array first
	if json.Unmarshal(data, &items) != nil || len(items) == 0 {
		items = nil
		// Try object — check for common envelope patterns (results, data, items)
		var envelope map[string]json.RawMessage
		if json.Unmarshal(data, &envelope) == nil {
			for _, key := range []string{"results", "data", "items"} {
				if raw, ok := envelope[key]; ok {
					var arr []json.RawMessage
					if json.Unmarshal(raw, &arr) == nil && len(arr) > 0 {
						items = arr
						break
					}
				}
			}
			// Single object with an id field (e.g., detail response)
			if items == nil {
				if _, ok := envelope["id"]; ok {
					_, _, _ = db.UpsertBatch(resourceType, []json.RawMessage{data})
					return
				}
			}
		}
	}

	if len(items) > 0 {
		_, _, _ = db.UpsertBatch(resourceType, items)
	}
}

// resolveLocal reads data from the local SQLite store.
// Item-list endpoints are routed through resolveLocalItemList so supported
// Zotero filters/scopes are applied locally. Other endpoints fall back to a
// generic resource dump and warn when request params cannot be reproduced.
func resolveLocal(ctx context.Context, resourceType string, isList bool, path string, params map[string]string, reason string) (json.RawMessage, DataProvenance, error) {
	db, err := openStoreForRead(ctx, "zotio")
	if err != nil {
		return nil, DataProvenance{}, fmt.Errorf("opening local database: %w\nRun 'zotio sync' first.", err)
	}
	if db == nil {
		return nil, DataProvenance{}, fmt.Errorf("no local data. Run 'zotio sync' first")
	}
	defer db.Close()

	prov := localProvenance(db, resourceType, reason)

	// PATCH(glean cvl6): Zotero-aware local query planner. For item-list reads
	// (/items, /items/top, /collections/{key}/items[/top]) apply the same
	// scopes the live endpoint would (itemType, tag, collection, top-level,
	// quick-search, sort, direction, limit, start) instead of dumping all
	// synced rows. Keyed on the path so it also covers the collection-items
	// command, which labels its resource "collections".
	if data, handled, qErr := resolveLocalItemList(db, path, params); handled {
		if qErr != nil {
			return nil, DataProvenance{}, qErr
		}
		itemProv := localProvenance(db, "items", reason)
		itemProv.Scoped = true
		return data, itemProv, nil
	}

	// Warn only when this generic read carries filters local data can't
	// reproduce. limit/start are applied below, so they never warrant a warning.
	// PATCH(glean zotero-pp-cli-2465cdde5e1cb719, slice B): keep the warning
	// scoped to genuinely unreproducible filters; item-list filters returned
	// above are already applied.
	if hasUnreproducibleParams(params) {
		fmt.Fprintf(os.Stderr, "warning: local data may be unfiltered — this endpoint's filters are not applied to cached data\n")
	}

	// PATCH(glean bugfix): list-shaped base paths must dump all local rows
	// even when the generated command passed isList=false.
	if isLocalListRead(resourceType, isList, path) {
		raw, err := db.List(resourceType, 0) // 0 = no limit, return all synced data
		if err != nil {
			return nil, DataProvenance{}, fmt.Errorf("querying local store: %w", err)
		}
		// Filter out empty/invalid records (empty arrays, null, whitespace-only)
		// that can end up in the store from pagination boundary artifacts.
		var items []json.RawMessage
		for _, r := range raw {
			trimmed := strings.TrimSpace(string(r))
			if trimmed == "" || trimmed == "null" || trimmed == "[]" || trimmed == "{}" {
				continue
			}
			items = append(items, r)
		}
		if len(items) == 0 {
			return nil, DataProvenance{}, fmt.Errorf("no local data for %q. Run 'zotio sync' first", resourceType)
		}
		// PATCH(glean zotero-pp-cli-2465cdde5e1cb719, slice B): apply start
		// offset then limit so paginated local list reads mirror the live API
		// (limit is also re-applied by the caller's truncateJSONArray).
		items = paginateLocalRows(items, params)
		if len(items) == 0 {
			return json.RawMessage("[]"), prov, nil
		}
		// Marshal []json.RawMessage into a single JSON array
		data, err := json.Marshal(items)
		if err != nil {
			return nil, DataProvenance{}, fmt.Errorf("marshaling local data: %w", err)
		}
		return data, prov, nil
	}

	// Get by ID — extract the last path segment as the ID
	parts := strings.Split(strings.TrimRight(path, "/"), "/")
	id := parts[len(parts)-1]

	item, err := db.Get(resourceType, id)
	if err != nil {
		return nil, DataProvenance{}, fmt.Errorf("querying local store: %w", err)
	}
	if item == nil {
		return nil, DataProvenance{}, fmt.Errorf("resource %q with ID %q not found in local store. Run 'zotio sync' first", resourceType, id)
	}
	return item, prov, nil
}

// reproducibleLocalParams are request params a generic local list read can
// honor (pagination) or that don't filter the row set (output format), so they
// must not trigger the "local data may be unfiltered" warning. PATCH(glean
// zotero-pp-cli-2465cdde5e1cb719, slice B).
var reproducibleLocalParams = map[string]bool{"limit": true, "start": true, "format": true}

// hasUnreproducibleParams reports whether params contains any filter a generic
// local read cannot reproduce (anything outside reproducibleLocalParams).
func hasUnreproducibleParams(params map[string]string) bool {
	for k, v := range params {
		if v == "" {
			continue
		}
		if !reproducibleLocalParams[k] {
			return true
		}
	}
	return false
}

// paginateLocalRows applies the Zotero start offset then limit to a generic
// local list result so paginated reads mirror the live API. An out-of-range
// start yields an empty slice (a live page past the end). PATCH(glean
// zotero-pp-cli-2465cdde5e1cb719, slice B).
func paginateLocalRows(rows []json.RawMessage, params map[string]string) []json.RawMessage {
	if start, _ := strconv.Atoi(params["start"]); start > 0 {
		if start >= len(rows) {
			return nil
		}
		rows = rows[start:]
	}
	if limit, _ := strconv.Atoi(params["limit"]); limit > 0 && limit < len(rows) {
		rows = rows[:limit]
	}
	return rows
}

// resolveLocalItemList runs the Zotero-aware item query planner when the path
// is an item-list endpoint, returning (data, true, err). It returns
// (nil, false, nil) for non-item-list paths so the caller falls back to its
// generic get/list handling. An empty match yields a JSON empty array, which
// mirrors a live list that matched nothing. PATCH(glean cvl6).
func resolveLocalItemList(db *store.Store, path string, params map[string]string) (json.RawMessage, bool, error) {
	collectionKey, parentKey, topOnly, isList := parseItemListPath(path)
	if !isList {
		return nil, false, nil
	}
	q := store.ItemQuery{
		ItemType:   params["itemType"],
		Tag:        params["tag"],
		Collection: collectionKey,
		Parent:     parentKey,
		TopOnly:    topOnly,
		Query:      params["q"],
		Sort:       params["sort"],
		Direction:  params["direction"],
	}
	if v := params["limit"]; v != "" {
		q.Limit, _ = strconv.Atoi(v)
	}
	if v := params["start"]; v != "" {
		q.Start, _ = strconv.Atoi(v)
	}
	items, err := db.QueryItems(q)
	if err != nil {
		return nil, true, fmt.Errorf("local item query: %w", err)
	}
	if len(items) == 0 {
		return json.RawMessage("[]"), true, nil
	}
	data, err := json.Marshal(items)
	if err != nil {
		return nil, true, fmt.Errorf("marshaling local items: %w", err)
	}
	return data, true, nil
}

// parseItemListPath classifies a Zotero API path as an item-list endpoint and
// extracts the collection key, parent key, and top-level flag. Recognizes
// /items, /items/top, /collections/{key}/items[/top], and
// /items/{key}/children (scoped to a parent's child items). PATCH(glean cvl6,
// glean zotero-pp-cli-2465cdde5e1cb719).
func parseItemListPath(path string) (collectionKey, parentKey string, topOnly, isList bool) {
	segs := strings.Split(strings.Trim(path, "/"), "/")
	switch {
	case len(segs) == 1 && segs[0] == "items":
		return "", "", false, true
	case len(segs) == 2 && segs[0] == "items" && segs[1] == "top":
		return "", "", true, true
	case len(segs) == 3 && segs[0] == "items" && segs[2] == "children":
		return "", segs[1], false, true
	case len(segs) >= 3 && segs[0] == "collections" && segs[2] == "items":
		return segs[1], "", len(segs) >= 4 && segs[3] == "top", true
	}
	return "", "", false, false
}

// Ensure time import is used (compilation guard).
var _ = time.Now
