// Copyright 2026 enieuwy. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"bytes"
	"fmt"
	"net/http"
	"net/netip"
	neturl "net/url"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// DeliverSink describes where command output should be routed when
// --deliver is set. Parsed from the sink specifier "scheme:target".
type DeliverSink struct {
	Scheme string
	Target string
}

var allowPrivateOutboundForTests bool

// ParseDeliverSink parses a --deliver value. Supported schemes:
//
//	stdout          -> default, no redirection
//	file:<path>     -> write output atomically to <path>
//	webhook:<url>   -> POST output body to <url>
//
// Returns an error for unknown schemes with a message naming the
// supported set, so agents see a structured refusal rather than a
// silent misroute.
func ParseDeliverSink(spec string) (DeliverSink, error) {
	if spec == "" || spec == "stdout" {
		return DeliverSink{Scheme: "stdout"}, nil
	}
	idx := strings.Index(spec, ":")
	if idx == -1 {
		return DeliverSink{}, fmt.Errorf("unknown --deliver sink %q: expected scheme:target (supported: stdout, file:<path>, webhook:<url>)", spec)
	}
	scheme := spec[:idx]
	target := spec[idx+1:]
	switch scheme {
	case "file":
		if target == "" {
			return DeliverSink{}, fmt.Errorf("--deliver file:<path> requires a path")
		}
	case "webhook":
		// PATCH(glean zotero-pp-cli-a8f9611224e937cc): reject private/internal
		// webhook targets before any command output can be POSTed to them.
		if err := validateExternalHTTPURL(target, false); err != nil {
			return DeliverSink{}, fmt.Errorf("--deliver webhook:<url> rejected: %w", err)
		}
	default:
		return DeliverSink{}, fmt.Errorf("unknown --deliver scheme %q (supported: stdout, file, webhook)", scheme)
	}
	return DeliverSink{Scheme: scheme, Target: target}, nil
}

// Deliver routes a captured output buffer to the configured sink. stdout
// is a no-op because the buffer has already been streamed to stdout via
// the MultiWriter set up in root.go.
func Deliver(sink DeliverSink, body []byte, compact bool) error {
	switch sink.Scheme {
	case "", "stdout":
		return nil
	case "file":
		return deliverFile(sink.Target, body)
	case "webhook":
		return deliverWebhook(sink.Target, body, compact)
	default:
		return fmt.Errorf("unsupported deliver sink %q", sink.Scheme)
	}
}

func deliverFile(path string, body []byte) error {
	// Atomic write: tmp + rename. Protects agents from seeing a partial
	// file if the process is interrupted mid-write.
	dir := filepath.Dir(path)
	if dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("creating deliver dir: %w", err)
		}
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, body, 0o600); err != nil {
		return fmt.Errorf("writing deliver tmp: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("replacing deliver file: %w", err)
	}
	return nil
}

// validateExternalHTTPURL rejects schemes and hosts that would let optional
// outbound integrations probe local/private networks. requireHTTPS is used for
// background telemetry-style sends where plaintext HTTP is never needed.
func validateExternalHTTPURL(raw string, requireHTTPS bool) error {
	u, err := neturl.Parse(strings.TrimSpace(raw))
	if err != nil {
		return fmt.Errorf("invalid URL %q: %w", raw, err)
	}
	scheme := strings.ToLower(u.Scheme)
	if requireHTTPS {
		if scheme != "https" {
			return fmt.Errorf("requires an https:// URL")
		}
	} else if scheme != "http" && scheme != "https" {
		return fmt.Errorf("requires an http:// or https:// URL")
	}
	host := u.Hostname()
	if host == "" {
		return fmt.Errorf("URL must include a host")
	}
	if !allowPrivateOutboundForTests && outboundHostIsPrivate(host) {
		return fmt.Errorf("host %q is local or private", host)
	}
	return nil
}

func outboundHostIsPrivate(host string) bool {
	h := strings.TrimSuffix(strings.ToLower(strings.TrimSpace(host)), ".")
	switch h {
	case "", "localhost", "ip6-localhost", "ip6-loopback":
		return true
	}
	if strings.HasSuffix(h, ".localhost") || strings.HasSuffix(h, ".local") {
		return true
	}
	if addr, err := netip.ParseAddr(h); err == nil {
		cgn := netip.MustParsePrefix("100.64.0.0/10")
		return addr.IsLoopback() || addr.IsPrivate() || addr.IsLinkLocalUnicast() || addr.IsLinkLocalMulticast() || addr.IsMulticast() || addr.IsUnspecified() || cgn.Contains(addr)
	}
	// Single-label names usually resolve only inside a private DNS suffix.
	return !strings.Contains(h, ".")
}

func deliverWebhook(url string, body []byte, compact bool) error {
	// PATCH(glean zotero-pp-cli-a8f9611224e937cc): keep direct helper calls as
	// constrained as the public --deliver parser.
	if err := validateExternalHTTPURL(url, false); err != nil {
		return err
	}
	contentType := "application/json"
	if compact {
		contentType = "application/x-ndjson"
	}
	req, err := http.NewRequest(http.MethodPost, url, bytes.NewReader(body))
	if err != nil {
		return fmt.Errorf("building webhook request: %w", err)
	}
	req.Header.Set("Content-Type", contentType)
	req.Header.Set("User-Agent", "zotero-pp-cli/deliver")

	client := &http.Client{Timeout: 30 * time.Second, CheckRedirect: func(req *http.Request, via []*http.Request) error {
		// PATCH(glean zotero-pp-cli-a8f9611224e937cc): do not follow webhook
		// redirects; a public URL must not bounce into a private service.
		return http.ErrUseLastResponse
	}}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("posting to webhook: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return fmt.Errorf("webhook returned %s", resp.Status)
	}
	return nil
}
