// Copyright 2026 enieuwy. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"net/url"
	"os"
	"strconv"

	"github.com/spf13/cobra"
)

func newItemsUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyTitle string
	var bodyAbstractNote string
	var bodyTags string
	var bodyCollections string
	var bodyExtra string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "update <itemKey>",
		Short: "Update a specific item",
		// PATCH(glean zotero-pp-cli-76875fc8c78bd05c): use an item-key placeholder, not an API-token placeholder.
		Example:     "  zotero-pp-cli items update ABCD1234 --title \"Updated title\"",
		Annotations: map[string]string{"pp:endpoint": "items.update", "pp:method": "PATCH", "pp:path": "/items/{itemKey}"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			// PATCH: route through the write target and supply the version precondition
			// Zotero requires for key-based writes (PATCH returns HTTP 428 without
			// If-Unmodified-Since-Version). Mirrors items delete; the version GET and the
			// PATCH hit the same library, so an item created on the web but not yet synced
			// locally still resolves. An explicit version in a --stdin body is respected.
			c, err := flags.newWriteClient()
			if err != nil {
				return err
			}
			// PATCH(glean zotero-pp-cli-1b05b22e1aeb8dd6): encode the item key as a single Zotero path segment.
			path := replacePathParam("/items/{itemKey}", "itemKey", url.PathEscape(args[0]))
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyTitle != "" {
					body["title"] = bodyTitle
				}
				if bodyAbstractNote != "" {
					body["abstractNote"] = bodyAbstractNote
				}
				if bodyTags != "" {
					var parsedTags any
					if err := json.Unmarshal([]byte(bodyTags), &parsedTags); err != nil {
						return fmt.Errorf("parsing --tags JSON: %w", err)
					}
					body["tags"] = parsedTags
				}
				if bodyCollections != "" {
					var parsedCollections any
					if err := json.Unmarshal([]byte(bodyCollections), &parsedCollections); err != nil {
						return fmt.Errorf("parsing --collections JSON: %w", err)
					}
					body["collections"] = parsedCollections
				}
				if bodyExtra != "" {
					body["extra"] = bodyExtra
				}
			}
			patchHeaders := map[string]string{}
			if _, hasVersion := body["version"]; !hasVersion {
				if _, v, verr := c.GetWithVersion(path, nil); verr == nil && v > 0 {
					patchHeaders["If-Unmodified-Since-Version"] = strconv.Itoa(v)
				}
			}
			data, statusCode, err := c.PatchWithHeaders(path, body, patchHeaders)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "patch",
					"resource": "items",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyTitle, "title", "", "Item title")
	cmd.Flags().StringVar(&bodyAbstractNote, "abstract-note", "", "Abstract or summary")
	cmd.Flags().StringVar(&bodyTags, "tags", "", "Tags to apply (array of {tag: string} objects)")
	cmd.Flags().StringVar(&bodyCollections, "collections", "", "Collection keys to assign this item to")
	cmd.Flags().StringVar(&bodyExtra, "extra", "", "Extra notes field (also stores Better BibTeX citation key)")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
