// Copyright 2026 enieuwy. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newItemsTopCmd(flags *rootFlags) *cobra.Command {
	var flagLimit int
	var flagStart int
	var flagSort string
	var flagTag string
	var flagItemType string
	var flagQ string

	cmd := &cobra.Command{
		Use:         "top",
		Short:       "List top-level items only (excludes attachments and notes)",
		Example:     "  zotio items top",
		Annotations: map[string]string{"pp:endpoint": "items.top", "pp:method": "GET", "pp:path": "/items/top", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/items/top"
			params := map[string]string{}
			if flagLimit != 0 {
				params["limit"] = fmt.Sprintf("%v", flagLimit)
			}
			if flagStart != 0 {
				params["start"] = fmt.Sprintf("%v", flagStart)
			}
			if flagSort != "" {
				params["sort"] = fmt.Sprintf("%v", flagSort)
			}
			if flagTag != "" {
				params["tag"] = fmt.Sprintf("%v", flagTag)
			}
			if flagItemType != "" {
				params["itemType"] = fmt.Sprintf("%v", flagItemType)
			}
			if flagQ != "" {
				params["q"] = fmt.Sprintf("%v", flagQ)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "items", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Honor --limit when the API accepts but ignores ?limit=N.
			data = truncateJSONArray(data, flagLimit)
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "Maximum number of items to return")
	cmd.Flags().IntVar(&flagStart, "start", 0, "Pagination offset")
	cmd.Flags().StringVar(&flagSort, "sort", "", "Sort field")
	cmd.Flags().StringVar(&flagTag, "tag", "", "Filter by tag")
	cmd.Flags().StringVar(&flagItemType, "item-type", "", "Filter by item type")
	cmd.Flags().StringVar(&flagQ, "query", "", "Quick search query")

	return cmd
}
