// Copyright 2026 enieuwy. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSchemaCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "schema",
		Short: "Zotero item type and field schema",
	}

	cmd.AddCommand(newSchemaCreatorFieldsCmd(flags))
	cmd.AddCommand(newSchemaItemFieldsCmd(flags))
	cmd.AddCommand(newSchemaItemTypeCreatorTypesCmd(flags))
	cmd.AddCommand(newSchemaItemTypeFieldsCmd(flags))
	cmd.AddCommand(newSchemaItemTypesCmd(flags))
	cmd.AddCommand(newSchemaNewItemTemplateCmd(flags))
	return cmd
}
