// Copyright 2026 enieuwy. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTagsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "tags",
		Short: "Manage tags across your Zotero library",
	}

	cmd.AddCommand(newTagsGetCmd(flags))
	cmd.AddCommand(newTagsListCmd(flags))
	// PATCH: Register hand-written Zotero tag workflows added after generation.
	cmd.AddCommand(newTagsAuditCmd(flags))
	cmd.AddCommand(newTagsInventoryCmd(flags))
	cmd.AddCommand(newTagsRenameCmd(flags))
	return cmd
}
