// Copyright 2026 enieuwy. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/signal"
	"strconv"
	"syscall"
	"time"

	"github.com/spf13/cobra"
	"zotero-pp-cli/internal/client"
	"zotero-pp-cli/internal/store"
)

func newTailCmd(flags *rootFlags) *cobra.Command {
	var resource string
	var interval time.Duration
	var follow bool
	// PATCH(glean a91x): tail persists a per-resource version cursor.
	var dbPath string

	cmd := &cobra.Command{
		Use:         "tail [resource]",
		Short:       "Stream live changes by polling the API at regular intervals",
		Annotations: map[string]string{"mcp:read-only": "true"},
		Long: `Tail streams live data changes by polling the API at configurable intervals.
Events are emitted as NDJSON to stdout for piping to other tools.
Gracefully shuts down on SIGTERM/SIGINT.

Note: For APIs with WebSocket or SSE support, a future version will use
native streaming instead of polling.`,
		Example: `  # Tail all changes every 10 seconds
  zotero-pp-cli tail --interval 10s

  # Tail a specific resource
  zotero-pp-cli tail messages --interval 5s

  # Pipe to jq for filtering
  zotero-pp-cli tail events --interval 30s | jq 'select(.type == "error")'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 {
				resource = args[0]
			}
			// JSON help envelope: when called with no resource AND --json,
			// surface the list of known resources so agents can discover
			// what to pass without parsing a usage error message.
			// Envelope: {resources: [...], note}.
			if resource == "" && flags.asJSON {
				return printJSONFiltered(cmd.OutOrStdout(), map[string]any{
					"resources": tailKnownResources(),
					"note":      "tail requires a resource name; pass one of the listed names",
				}, flags)
			}
			if resource == "" {
				return fmt.Errorf("resource name required (e.g., 'tail items')")
			}

			c, err := flags.newClient()
			if err != nil {
				return err
			}
			c.NoCache = true

			// PATCH(glean a91x): resolve the real change-feed endpoint
			// (items -> /items, etc.); rejects non-change-feed resources.
			path, err := syncResourcePath(resource)
			if err != nil {
				return err
			}

			// PATCH(glean a91x): open the local store so each poll resumes
			// from the per-resource version cursor instead of re-fetching all.
			if dbPath == "" {
				dbPath = defaultDBPath("zotero-pp-cli")
			}
			db, err := store.OpenWithContext(cmd.Context(), dbPath)
			if err != nil {
				return fmt.Errorf("opening local database: %w", err)
			}
			defer db.Close()

			// PATCH(glean a91x): tail streams live and owns delivery per
			// cycle; nil the deliver buffer so root.go's post-run flush
			// never fires (it would buffer the whole stream forever).
			sink := flags.deliverSink
			flags.deliverBuf = nil

			sig := make(chan os.Signal, 1)
			signal.Notify(sig, syscall.SIGTERM, syscall.SIGINT)

			ticker := time.NewTicker(interval)
			defer ticker.Stop()

			fmt.Fprintf(os.Stderr, "Tailing %s every %s (Ctrl+C to stop)\n", resource, interval)

			// Initial poll
			if err := emitChanges(c, db, resource, path, sink, os.Stdout); err != nil {
				fmt.Fprintf(os.Stderr, "warning: initial poll failed: %v\n", err)
			}

			// PATCH(glean a91x): honor --follow=false as a single poll.
			if !follow {
				return nil
			}

			for {
				select {
				case <-sig:
					fmt.Fprintln(os.Stderr, "\nShutting down gracefully...")
					return nil
				case <-ticker.C:
					if err := emitChanges(c, db, resource, path, sink, os.Stdout); err != nil {
						fmt.Fprintf(os.Stderr, "warning: poll failed: %v\n", err)
					}
				}
			}
		},
	}

	cmd.Flags().StringVar(&resource, "resource", "", "Resource type to tail")
	cmd.Flags().DurationVar(&interval, "interval", 10*time.Second, "Poll interval")
	cmd.Flags().BoolVar(&follow, "follow", true, "Keep running (set --follow=false for single poll)")
	// PATCH(glean a91x): cursor persistence location.
	cmd.Flags().StringVar(&dbPath, "db", "", "Database path (default: ~/.local/share/zotero-pp-cli/data.db)")

	return cmd
}

// tailKnownResources returns the change-feed resources tail can stream.
// PATCH(glean a91x): restricted to the four resources with a /deleted
// bucket (schema has no change feed and is dropped).
func tailKnownResources() []string {
	return []string{
		"collections",
		"items",
		"searches",
		"tags",
	}
}

// emitChanges polls one resource for changes since the stored tail cursor,
// emits upsert/delete NDJSON events for the cycle, routes them to the deliver
// sink, and advances the cursor. PATCH(glean a91x): tail is now a deduplicated
// version-cursor change feed rather than a full re-fetch each poll. The cursor
// is namespaced "tail:<resource>" in sync_state so it never collides with
// sync's own checkpoint.
func emitChanges(c *client.Client, db *store.Store, resource, path string, sink DeliverSink, w io.Writer) error {
	cursorKey := "tail:" + resource
	cursor, _ := db.GetLibraryVersion(cursorKey)

	params := map[string]string{}
	if cursor > 0 {
		params["since"] = strconv.Itoa(cursor)
	}

	body, newVer, err := c.GetWithVersion(path, params)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	now := time.Now().UTC().Format(time.RFC3339)

	items, _, _ := extractPageItems(body, "")
	for _, item := range items {
		var obj map[string]any
		if err := json.Unmarshal(item, &obj); err != nil {
			continue
		}
		event := map[string]any{
			"event":     "upsert",
			"resource":  resource,
			"key":       fmt.Sprintf("%v", store.LookupFieldValue(obj, "key")),
			"version":   store.LookupFieldValue(obj, "version"),
			"timestamp": now,
			"data":      obj,
		}
		if err := enc.Encode(event); err != nil {
			return err
		}
	}

	// Deletions only make sense once a baseline cursor exists: the first
	// poll (cursor == 0) emits the full current set as upserts and skips
	// /deleted, which is the intended change-feed bootstrap.
	if cursor > 0 {
		delBody, _, derr := c.GetWithVersion("/deleted", params)
		if derr != nil {
			fmt.Fprintf(os.Stderr, "warning: tail %s: fetching deletions failed: %v\n", resource, derr)
		} else {
			var buckets map[string][]string
			if err := json.Unmarshal(delBody, &buckets); err == nil {
				for _, k := range buckets[resource] {
					event := map[string]any{
						"event":     "delete",
						"resource":  resource,
						"key":       k,
						"timestamp": now,
					}
					if err := enc.Encode(event); err != nil {
						return err
					}
				}
			}
		}
	}

	out := buf.Bytes()
	if len(out) > 0 {
		if _, err := w.Write(out); err != nil {
			return err
		}
		switch sink.Scheme {
		case "webhook":
			if err := deliverWebhook(sink.Target, out, true); err != nil {
				fmt.Fprintf(os.Stderr, "warning: tail %s: webhook delivery failed: %v\n", resource, err)
			}
		case "file":
			f, ferr := os.OpenFile(sink.Target, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o600)
			if ferr != nil {
				fmt.Fprintf(os.Stderr, "warning: tail %s: file delivery failed: %v\n", resource, ferr)
			} else {
				if _, werr := f.Write(out); werr != nil {
					fmt.Fprintf(os.Stderr, "warning: tail %s: file delivery failed: %v\n", resource, werr)
				}
				_ = f.Close()
			}
		}
	}

	if newVer > cursor {
		_ = db.SaveLibraryVersion(cursorKey, newVer)
	}
	return nil
}
