// Copyright 2026 OrgMentem. Licensed under MIT. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

// whichEntry is one row of the curated capability index. The index is
// seeded at generation time from the same NovelFeature list that drives
// the SKILL.md feature section, so the command a `which` query returns
// is guaranteed to exist and to match what the skill advertises.
type whichEntry struct {
	Command      string `json:"command"`
	Description  string `json:"description"`
	Group        string `json:"group,omitempty"`
	WhyItMatters string `json:"why_it_matters,omitempty"`
}

// whichIndex is the curated list of capabilities this CLI advertises as
// its hero features. Endpoint-level commands are discoverable via
// `--help`; `which` exists to resolve a natural-language capability
// query to one of the commands the skill says matter most.
// PATCH(marketing-heroes): rebuilt around the shipped roadmap flagships
// (library health, reviewable import, enrich, journal undo, export
// snapshot, vault sync, summarize, preprint-check fix) — the print-time
// seed predated Phases 1-8 and advertised only hygiene/reading primitives.
var whichIndex = []whichEntry{
	// Library trust & health — catch the reference problems that break downstream.
	{Command: "library health", Description: "Ranked, CI-gateable health report: citekey conflicts, duplicates, missing metadata, tag drift, broken attachments — with --for presets for citation or systematic-review readiness.", Group: "Library trust & health", WhyItMatters: "Run this before any bibliography export or screening handoff; gate CI with --fail-on (exit 11) and publish a shields.io badge with --badge."},
	{Command: "items duplicates", Description: "Detect likely duplicate items by DOI or normalized title, then merge them safely with `duplicates resolve` — preview-first.", Group: "Library trust & health", WhyItMatters: "Duplicates corrupt PRISMA counts and double-cite sources; resolve them before they reach a manuscript."},
	// PATCH(marketing-heroes-2): research-integrity + gap-analysis heroes.
	{Command: "items retract-check", Description: "Find retracted papers in your library: checks every DOI-bearing item against Crossref's Retraction Watch data — retractions, expressions of concern, and corrections, with notice DOIs and dates.", Group: "Library trust & health", WhyItMatters: "Citing a retracted paper is a career-level embarrassment; catch it before a reviewer does (also gates library health via --check-retractions)."},
	{Command: "collections gaps", Description: "Rank the papers your collection cites most that are missing from your library — citation-graph gap analysis via OpenCitations and Semantic Scholar.", Group: "Library trust & health", WhyItMatters: "A reviewer will ask why you didn't cite the field's most-cited work; find the gap before they do, then import doi it."},
	{Command: "tags audit", Description: "Find and fix tag drift: groups tags that differ only by case or variant, shows item counts, and generates ready-to-run merge commands.", Group: "Library trust & health", WhyItMatters: "Use this before any literature review handoff to clean up tag taxonomy; dirty tags produce unreliable filtered exports."},
	{Command: "items audit", Description: "Count and list items missing PDFs, abstracts, DOIs, or tags — one command for a complete metadata health report.", Group: "Library trust & health", WhyItMatters: "Use this before a systematic review export to identify items that need metadata enrichment."},
	{Command: "items missing-pdf", Description: "List journal articles and book chapters that have no attached PDF — your download queue, ready to script.", Group: "Library trust & health", WhyItMatters: "Use this to batch-generate a download list for Unpaywall or Sci-Hub scripts."},
	{Command: "library stats", Description: "See your library broken down by item type, publication year, and top journals — a dashboard in one command.", Group: "Library trust & health", WhyItMatters: "Use this to understand the shape and bias of a library before a systematic review or citation audit."},
	// PATCH: schema-drift probe entry (hand-written command, not generator-seeded).
	{Command: "schema drift", Description: "Detect what a Zotero upgrade changed: new or removed item types, fields, and creator fields vs a saved baseline.", Group: "Library trust & health", WhyItMatters: "Use this after upgrading Zotero to find item types or fields a new version added that your tooling may not model yet."},

	// Safe writes & import — preview-first change with an undo trail.
	{Command: "import scan", Description: "Reviewable ingest: triage a folder of PDFs against your library (new vs duplicate vs attach-candidate), resolve metadata, then apply schema-valid creates from an editable manifest.", Group: "Safe writes & import", WhyItMatters: "Bulk-import without making a mess — every create is previewed, deduplicated, and schema-validated before it touches your library."},
	{Command: "import doi", Description: "Turn a DOI, PMID, arXiv ID, or ISBN into a schema-valid Zotero item — one command per identifier (import doi|pmid|arxiv|isbn).", Group: "Safe writes & import", WhyItMatters: "Add a paper from a citation you found without opening a browser or hand-typing metadata."},
	{Command: "items enrich", Description: "Fill missing DOIs, abstracts, and open-access PDF links from CrossRef, OpenAlex, Semantic Scholar, and Unpaywall — preview-first, with provenance appended to each item.", Group: "Safe writes & import", WhyItMatters: "Turn the audit's missing-metadata queue into applied fixes; --validate cross-checks stored DOIs read-only."},
	{Command: "items preprint-check", Description: "Find arXiv preprints that have since been published in a journal (via CrossRef) — and upgrade them with the published DOI using `preprint-check fix`, preview-first.", Group: "Safe writes & import", WhyItMatters: "Citing a preprint when a journal version exists undermines a bibliography; this catches and fixes it in one pass."},
	{Command: "journal undo", Description: "Every applied write is journaled; `journal undo <run-id>` reverses reversible runs (tag renames, collection moves) and loudly refuses the rest.", Group: "Safe writes & import", WhyItMatters: "Batch writes are only safe when you can see what ran and take it back; this is the take-it-back."},

	// Agent & automation surface — trustworthy context for scripts, CI, and MCP hosts.
	{Command: "items summarize", Description: "Assemble a bounded, synthesis-ready context bundle for an item or collection — citation, abstract, your annotations, a capped fulltext excerpt — without ever calling a model.", Group: "Agent & automation surface", WhyItMatters: "Hand an LLM exactly the high-signal context it needs for a literature synthesis, bounded and provenance-tagged."},
	{Command: "export snapshot", Description: "Reproducible, resumable full-library export (JSONL) with a lockfile recording each item's key, version, and content hash.", Group: "Agent & automation surface", WhyItMatters: "Prove what changed between two review handoffs by diffing lockfiles instead of eyeballing exports."},
	{Command: "watch", Description: "Keep the local store fresh with periodic incremental syncs (--interval, --once); --health diffs library health between cycles and reports new findings to stdout or a webhook.", Group: "Agent & automation surface", WhyItMatters: "Run it in the background so agents and scripts never read stale data — and hear about new problems the cycle they appear."},
	{Command: "workflow run", Description: "Run a declarative multi-step workflow spec (JSON) in-process, with per-step status and continue-on-error control.", Group: "Agent & automation surface", WhyItMatters: "Chain sync → audit → export into one reviewable spec instead of a brittle shell script."},
	{Command: "vault sync", Description: "Two-way Obsidian/Logseq vault sync: one Markdown note per item, managed blocks that never clobber your prose, conflict-safe write-back via push/pull/resolve.", Group: "Agent & automation surface", WhyItMatters: "Keep a PKM vault and Zotero in lockstep without losing hand-written notes on either side."},
	// PATCH(marketing-heroes-2): onboarding hero.
	{Command: "init", Description: "Guided first run: detect Zotero, enable the local API, set the Web API key, first sync, and a quick health check — one command from install to working setup.", Group: "Agent & automation surface", WhyItMatters: "From install to a synced, health-checked library in under a minute; idempotent, and agent-safe under --no-input."},

	// Export & citations.
	{Command: "collections export", Description: "Export an entire collection and all its subcollections as a single BibTeX or CSL-JSON file, preserving structure in comments.", Group: "Export & citations", WhyItMatters: "Use this to hand a complete literature snapshot to LaTeX or to another researcher without losing the organizational hierarchy."},
	{Command: "items citekey-conflicts", Description: "Find items without a Better BibTeX citation key or with duplicate keys — prevent LaTeX compilation failures before they happen.", Group: "Export & citations", WhyItMatters: "Use this before exporting BibTeX for a LaTeX manuscript to catch key conflicts that cause \\cite{} failures."},
	// PATCH(marketing-heroes-2): manuscript-side citation checking.
	{Command: "items bibcheck", Description: "Check a manuscript (.tex or pandoc Markdown) against your library: every \\cite and @citekey resolved, unknown and ambiguous keys flagged.", Group: "Export & citations", WhyItMatters: "Run it before submission — unknown citekeys are LaTeX build failures waiting to happen; gate CI with --fail-on-unknown (exit 11)."},

	// Reading workflow.
	{Command: "reading-list", Description: "Surface your oldest unread papers sorted by date added — your reading backlog, oldest-first, with abstract preview.", Group: "Reading workflow", WhyItMatters: "Use this to fetch the next paper an agent should fetch fulltext for, or to triage a reading session."},
	{Command: "annotations export", Description: "Export all highlights and notes from a collection or tag set as a single markdown or JSON file, one section per paper.", Group: "Reading workflow", WhyItMatters: "Use this to pull a week of reading annotations into a markdown document for synthesis or AI summarization."},
	{Command: "annotations timeline", Description: "See your annotations ordered by date — find what you were reading and highlighting in any time window.", Group: "Reading workflow", WhyItMatters: "Use this to extract a week's reading highlights for synthesis or to reconstruct a research trail."},
	{Command: "items note-template", Description: "Generate a pre-filled markdown reading note (frontmatter + abstract + empty Annotations section) for any item — paste into Obsidian or Logseq.", Group: "Reading workflow", WhyItMatters: "Use this to initialize a reading note in a PKM system without manually copying fields from the Zotero UI."},
	{Command: "items open", Description: "Jump from CLI search results directly to the item in the Zotero desktop app.", Group: "Reading workflow", WhyItMatters: "Use this after finding an item via CLI search to open it for reading without leaving the terminal flow."},
	// PATCH(marketing-heroes-2): the shareable one.
	{Command: "library wrapped", Description: "Your Zotero year in review — items added by month and type, top venues and authors, annotation activity, PDF coverage — with a shareable SVG card (--card).", Group: "Reading workflow", WhyItMatters: "The fun one: see (and share) what your reading year actually looked like, straight from the local store."},
}

// whichMatch pairs an index entry with its ranking score for a query.
// Higher score means stronger match. The ranker is naive (exact token
// then substring then group tag) because 20-40 entries do not need
// semantic retrieval - a ranker upgrade is a future change that would
// not break this contract.
type whichMatch struct {
	Entry whichEntry `json:"entry"`
	Score int        `json:"score"`
}

// rankWhich returns up to `limit` best matches for `query` against the
// index, sorted by descending score. Score breakdown:
//
//	+3  exact token match on the command's leaf or full path
//	+2  whole query is a substring of the command or the description
//	+2  per meaningful query token found in the command or description
//	+1  per meaningful query token found in why-it-matters
//	+1  group tag contains a query token
//
// PATCH(marketing-heroes-2): per-token scoring over description and
// why-it-matters — goal-phrase queries ("retracted papers", "check
// manuscript") scored zero under whole-phrase-only matching.
//
// Ties break on declaration order in the index. An empty query returns
// every entry at score 0 in declaration order - this is the "list all"
// behavior the skill documents for broad agent discovery.
func rankWhich(index []whichEntry, query string, limit int) []whichMatch {
	if limit <= 0 {
		limit = 3
	}
	q := strings.ToLower(strings.TrimSpace(query))
	if q == "" {
		out := make([]whichMatch, 0, len(index))
		for _, e := range index {
			out = append(out, whichMatch{Entry: e, Score: 0})
		}
		return out
	}
	qTokens := strings.Fields(q)

	scored := make([]whichMatch, 0, len(index))
	for i, e := range index {
		score := whichScoreEntry(e, q, qTokens)
		scored = append(scored, whichMatch{Entry: e, Score: score})
		_ = i
	}

	sort.SliceStable(scored, func(i, j int) bool {
		return scored[i].Score > scored[j].Score
	})
	// Drop zero-score matches when the query was non-empty; agents
	// branching on exit code rely on "no match" meaning no confidence.
	filtered := scored[:0]
	for _, m := range scored {
		if m.Score > 0 {
			filtered = append(filtered, m)
		}
	}
	if len(filtered) > limit {
		filtered = filtered[:limit]
	}
	return filtered
}

// whichStopwords are query tokens too generic to signal intent; they are
// ignored by the per-token scorer so "how can I find the..." doesn't
// inflate every entry.
var whichStopwords = map[string]bool{
	"the": true, "and": true, "for": true, "are": true, "you": true,
	"your": true, "how": true, "can": true, "not": true, "with": true,
	"what": true, "all": true, "any": true, "get": true, "use": true,
}

func whichScoreEntry(e whichEntry, query string, qTokens []string) int {
	score := 0
	cmd := strings.ToLower(e.Command)
	cmdTokens := strings.Fields(cmd)
	desc := strings.ToLower(e.Description)
	why := strings.ToLower(e.WhyItMatters)
	group := strings.ToLower(e.Group)

	// Exact token match on the command path (any token).
	for _, qt := range qTokens {
		for _, ct := range cmdTokens {
			if qt == ct {
				score += 3
				break
			}
		}
	}
	// Whole-query substring bonuses (covers hyphenated leaves and phrases).
	if strings.Contains(cmd, query) {
		score += 2
	}
	if strings.Contains(desc, query) {
		score += 2
	}
	// Per-token substring scoring over command, description, and
	// why-it-matters. PATCH(marketing-heroes-2): see rankWhich doc.
	for _, qt := range qTokens {
		if len(qt) < 3 || whichStopwords[qt] {
			continue
		}
		if strings.Contains(cmd, qt) || strings.Contains(desc, qt) {
			score += 2
		}
		if why != "" && strings.Contains(why, qt) {
			score += 1
		}
	}
	// Group tag match.
	if group != "" {
		for _, qt := range qTokens {
			if strings.Contains(group, qt) {
				score += 1
				break
			}
		}
	}
	return score
}

func newWhichCmd(flags *rootFlags) *cobra.Command {
	var limit int
	cmd := &cobra.Command{
		Use:   "which [query]",
		Short: "Find the command that implements a capability",
		Annotations: map[string]string{
			"pp:typed-exit-codes": "0,2",
		},
		Long: `which resolves a natural-language capability query (for example, "search messages" or "stale tickets") to the best matching command from this CLI's curated feature index.

Exit codes:
  0  at least one match found
  2  no confident match - the query did not score against any indexed capability; fall back to '--help' or 'search' if this CLI has one`,
		Example: `  zotio which "stale tickets"
  zotio which "bottleneck"
  zotio which --limit 1 "send message"
  zotio which                                # list the full capability index`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(whichIndex) == 0 {
				return usageErr(fmt.Errorf("this CLI has no curated capability index; run '--help' to see every command"))
			}
			query := strings.Join(args, " ")
			matches := rankWhich(whichIndex, query, limit)

			// Empty query returns the whole index at score 0 (listing mode).
			if strings.TrimSpace(query) == "" {
				return renderWhich(cmd, flags, rankWhichAll(whichIndex))
			}

			if len(matches) == 0 {
				// Under --json, return an empty matches envelope at exit 0
				// so agents can branch on `matches.length == 0` instead of
				// parsing a usage error message. Non-JSON keeps the typed
				// exit-2 path so terminal users see the help hint.
				if flags.asJSON {
					return printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"matches": []whichMatch{},
					}, flags)
				}
				return usageErr(fmt.Errorf("no match for %q; try '%s --help' for the full command list", query, cmd.Root().Name()))
			}
			return renderWhich(cmd, flags, matches)
		},
	}
	cmd.Flags().IntVar(&limit, "limit", 3, "Maximum number of matches to return")
	return cmd
}

// rankWhichAll is a narrow helper used by the "empty query lists the
// index" path. It returns every entry in declaration order at score 0
// so the render path treats them uniformly.
func rankWhichAll(index []whichEntry) []whichMatch {
	out := make([]whichMatch, 0, len(index))
	for _, e := range index {
		out = append(out, whichMatch{Entry: e, Score: 0})
	}
	return out
}

func renderWhich(cmd *cobra.Command, flags *rootFlags, matches []whichMatch) error {
	w := cmd.OutOrStdout()
	// Output shape follows the same rule as every other generated
	// command: JSON when the caller asked for it OR when stdout is not
	// a terminal; table when a human is looking.
	asJSON := flags.asJSON
	if !asJSON && !isTerminal(w) {
		asJSON = true
	}
	if asJSON {
		// JSON envelope: {matches: [...]}. The wrap is critical:
		// printJSONFiltered's --compact path uses compactListFields
		// (allowlist) for top-level arrays, which would strip
		// entry/score keys; routing through compactObjectFields
		// (blocklist) via an object envelope preserves them.
		if matches == nil {
			matches = []whichMatch{}
		}
		return printJSONFiltered(w, map[string]any{"matches": matches}, flags)
	}
	fmt.Fprintf(w, "%-24s  %-8s  %s\n", "COMMAND", "SCORE", "DESCRIPTION")
	for _, m := range matches {
		fmt.Fprintf(w, "%-24s  %-8d  %s\n", m.Entry.Command, m.Score, m.Entry.Description)
	}
	return nil
}
