// notices-gen writes THIRD_PARTY_LICENSES.txt: the attribution file every
// release channel ships beside zotio's own LICENSE.
//
// The release binaries are static (CGO_ENABLED=0) and modernc.org/sqlite is a
// pure-Go transpile of SQLite, so BSD-3-Clause and Apache-2.0 code is linked
// into the artifact rather than loaded from the host. BSD-3-Clause clause 2
// conditions binary redistribution on reproducing the copyright notice,
// conditions, and disclaimer "in the documentation and/or other materials
// provided with the distribution"; Apache-2.0 section 4(a) requires giving
// recipients a copy of the License. An SBOM enumerates components and SPDX
// ids, so it does not satisfy either requirement.
//
// The module set is derived from the two released binaries (go list -deps on
// ./cmd/zotio and ./cmd/zotio-mcp, the ids .goreleaser.yaml builds), not from
// go.mod, so build tooling and test-only modules stay out and a newly linked
// dependency cannot slip through. Output is sorted by module path and
// therefore deterministic, which is what makes the CI drift gate meaningful.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

const outputPath = "THIRD_PARTY_LICENSES.txt"

// licenseNames are the file names, in preference order, that modules use for
// their license text. NOTICE is appended separately when present, because
// Apache-2.0 section 4(d) makes it additive rather than an alternative.
var licenseNames = []string{
	"LICENSE",
	"LICENSE.txt",
	"LICENSE.md",
	"LICENCE",
	"LICENCE.txt",
	"COPYING",
	"COPYING.txt",
}

var noticeNames = []string{"NOTICE", "NOTICE.txt", "NOTICE.md"}

type module struct {
	Path    string
	Version string
	Dir     string
	Main    bool
}

type pkg struct {
	Standard bool
	Module   *module
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "notices-gen:", err)
		os.Exit(1)
	}
}

func run() error {
	mods, err := linkedModules()
	if err != nil {
		return err
	}
	if len(mods) == 0 {
		return fmt.Errorf("no third-party modules resolved; refusing to write an empty %s", outputPath)
	}

	var b strings.Builder
	b.WriteString(header)
	for _, m := range mods {
		text, name, err := licenseText(m)
		if err != nil {
			return err
		}
		fmt.Fprintf(&b, "%s\n%s %s\n%s\n\n", separator, m.Path, m.Version, name)
		b.WriteString(strings.TrimRight(text, "\n"))
		b.WriteString("\n\n")
	}
	return os.WriteFile(outputPath, []byte(b.String()), 0o644)
}

const separator = "================================================================================"

const header = `THIRD-PARTY SOFTWARE NOTICES

zotio itself is distributed under the MIT License; see LICENSE. The binaries in
this distribution statically link the modules listed below, and their licenses
require that these notices travel with the binary.

This file is generated by cmd/notices-gen from the modules the released
binaries actually link. Do not edit it by hand; run "make notices" instead.

`

// releaseTargets are the GOOS/GOARCH pairs .goreleaser.yaml builds. The set of
// linked packages is platform-dependent — github.com/inconshreveable/mousetrap
// reaches the binary only on windows, through cobra — so a host-only scan
// would omit notices from the artifacts that need them.
var releaseTargets = [][2]string{
	{"darwin", "amd64"},
	{"darwin", "arm64"},
	{"linux", "amd64"},
	{"linux", "arm64"},
	{"windows", "amd64"},
	{"windows", "arm64"},
}

// linkedModules returns every non-main, non-stdlib module reachable from the
// released commands on any release target, deduplicated and sorted by module
// path.
func linkedModules() ([]module, error) {
	seen := map[string]module{}
	for _, target := range releaseTargets {
		if err := collectModules(target[0], target[1], seen); err != nil {
			return nil, err
		}
	}

	mods := make([]module, 0, len(seen))
	for _, m := range seen {
		mods = append(mods, m)
	}
	sort.Slice(mods, func(i, j int) bool { return mods[i].Path < mods[j].Path })
	return mods, nil
}

func collectModules(goos, goarch string, seen map[string]module) error {
	cmd := exec.Command("go", "list", "-deps", "-json", "./cmd/zotio", "./cmd/zotio-mcp")
	cmd.Env = append(os.Environ(), "GOOS="+goos, "GOARCH="+goarch)
	cmd.Stderr = os.Stderr
	out, err := cmd.Output()
	if err != nil {
		return fmt.Errorf("go list -deps for %s/%s: %w", goos, goarch, err)
	}
	dec := json.NewDecoder(bytes.NewReader(out))
	for {
		var p pkg
		if err := dec.Decode(&p); err == io.EOF {
			break
		} else if err != nil {
			return fmt.Errorf("decoding go list output for %s/%s: %w", goos, goarch, err)
		}
		if p.Standard || p.Module == nil || p.Module.Main {
			continue
		}
		seen[p.Module.Path] = *p.Module
	}
	return nil
}

// licenseText reads a module's license, plus its NOTICE when it ships one. A
// module with no readable license is a hard error: silently omitting it is the
// exact defect this generator exists to prevent.
func licenseText(m module) (text, name string, err error) {
	if m.Dir == "" {
		return "", "", fmt.Errorf("%s has no local module directory; run go mod download first", m.Path)
	}
	for _, candidate := range licenseNames {
		data, readErr := os.ReadFile(filepath.Join(m.Dir, candidate))
		if readErr != nil {
			continue
		}
		body := string(data)
		label := candidate
		for _, noticeName := range noticeNames {
			notice, noticeErr := os.ReadFile(filepath.Join(m.Dir, noticeName))
			if noticeErr != nil {
				continue
			}
			body = strings.TrimRight(body, "\n") + "\n\n--- " + noticeName + " ---\n\n" + string(notice)
			label = candidate + " + " + noticeName
			break
		}
		return body, label, nil
	}
	return "", "", fmt.Errorf("no license file found for %s in %s", m.Path, m.Dir)
}
