// Copyright 2026 OrgMentem. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cliutil

import (
	"html"
	"regexp"
	"strings"
	"time"
)

// CleanText normalizes scraped text by trimming whitespace and decoding
// HTML entities. Always use this when extracting strings from HTML or
// schema.org JSON-LD. Skipping this step is how recipe-goat's
// "The Food Lab&#39;s" bug shipped: schema.org strings passed through
// unescaped because the JSON-LD parser didn't normalize.
//
// Single unescape pass: "&amp;amp;" -> "&amp;" (matches html.UnescapeString
// stdlib behavior). If you need multiple passes you almost always have a
// deeper escaping problem upstream — fix there, not here.
// PATCH(glean 2kgy): unexported — only exercised by package tests today.
func cleanText(s string) string {
	return html.UnescapeString(strings.TrimSpace(s))
}

// ParseStoredTime parses timestamps read back from SQLite-backed generated
// stores. modernc.org/sqlite can serialize time.Time using Go's native
// time.String format, while hand-written sync code often stores RFC3339.
// Use this helper instead of a single time.Parse(time.RFC3339, value) call
// when scanning timestamp columns from the store.
func parseStoredTime(s string) time.Time {
	s = strings.TrimSpace(s)
	if s == "" {
		return time.Time{}
	}
	for _, layout := range []string{
		time.RFC3339Nano,
		time.RFC3339,
		"2006-01-02 15:04:05.999999999 -0700 MST",
		"2006-01-02 15:04:05.999999 -0700 MST",
		"2006-01-02 15:04:05.999 -0700 MST",
		"2006-01-02 15:04:05 -0700 MST",
		"2006-01-02 15:04:05.999999999 -0700",
		"2006-01-02 15:04:05 -0700",
	} {
		if t, err := time.Parse(layout, s); err == nil {
			return t
		}
	}
	return time.Time{}
}

// LooksLikeAuthError checks if an error message body contains auth-related keywords.
func LooksLikeAuthError(msg string) bool {
	lower := strings.ToLower(msg)
	patterns := []string{
		`\bkey\b`,
		`\btoken\b`,
		`\bunauthorized\b`,
		`\bapi_key\b`,
		`missing.{0,20}key`,
		`required.{0,20}key`,
		`\bforbidden\b`,
		`\bauthenticat`,
		`\bcredential`,
	}
	for _, p := range patterns {
		if matched, _ := regexp.MatchString(p, lower); matched {
			return true
		}
	}
	return false
}

// HTTPErrorKind classifies an API error by the HTTP status embedded in its
// message, so the CLI and MCP layers detect the same statuses in one place
// while each keeps its own user-facing hint text and result type.
// PATCH(glean static-audit): de-duplicates the brittle strings.Contains(msg,
// "HTTP NNN") ladder previously copy-pasted across internal/cli and internal/mcp.
type HTTPErrorKind int

const (
	HTTPErrOther HTTPErrorKind = iota
	HTTPErrConflict
	HTTPErrBadRequestAuth
	HTTPErrUnauthorized
	HTTPErrForbidden
	HTTPErrNotFound
	HTTPErrRateLimited
)

// ClassifyHTTPError maps an error message to an HTTPErrorKind by the HTTP
// status string it carries. Check order matches the historical CLI/MCP
// switches: 409, then 400-with-auth, 401, 403, 404, 429.
func ClassifyHTTPError(msg string) HTTPErrorKind {
	switch {
	case strings.Contains(msg, "HTTP 409"):
		return HTTPErrConflict
	case strings.Contains(msg, "HTTP 400") && LooksLikeAuthError(msg):
		return HTTPErrBadRequestAuth
	case strings.Contains(msg, "HTTP 401"):
		return HTTPErrUnauthorized
	case strings.Contains(msg, "HTTP 403"):
		return HTTPErrForbidden
	case strings.Contains(msg, "HTTP 404"):
		return HTTPErrNotFound
	case strings.Contains(msg, "HTTP 429"):
		return HTTPErrRateLimited
	default:
		return HTTPErrOther
	}
}

// credPatterns matches credential-shaped substrings in error bodies. Beyond
// the generic sk-/Bearer/key= shapes carried over from the generator template,
// it now recognizes this app's own Zotero-API-Key header scheme so a reflected
// or echoed key is redacted even though it carries no sk-/Bearer prefix.
// PATCH(glean zotio-c3c6d04bb48b7e67): added the (zotero-api-)key[:=] and
// Zotero-API-Key header forms; hoisted to package scope to compile once.
var credPatterns = regexp.MustCompile(`(?i)(sk-[a-zA-Z0-9]{8,}|sk_live_[a-zA-Z0-9]+|Bearer\s+[a-zA-Z0-9._\-]+|(?:zotero-api-)?key\s*[:=]\s*[a-zA-Z0-9._\-]+|zotero-api-key\s+[a-zA-Z0-9]{16,})`)

// SanitizeErrorBody truncates and strips credential-shaped strings from error output.
func SanitizeErrorBody(msg string) string {
	return SanitizeErrorBodyWithSecrets(msg)
}

// SanitizeErrorBodyWithSecrets redacts credential-shaped substrings and any
// literal secret supplied (e.g. the configured Zotero API key), then truncates.
// The explicit-secret pass runs before truncation so a key straddling the
// length cap is still caught, and covers a reflected key that has no prefix.
// PATCH(glean zotio-c3c6d04bb48b7e67): secret-aware redaction so the caller can
// pass the live credential; SanitizeErrorBody was previously dead code because
// classifyAPIError re-embedded the raw body via %w ahead of the sanitized copy.
func SanitizeErrorBodyWithSecrets(msg string, secrets ...string) string {
	for _, s := range secrets {
		if len(s) >= 8 {
			msg = strings.ReplaceAll(msg, s, "[REDACTED]")
		}
	}
	if len(msg) > 200 {
		msg = msg[:200] + "..."
	}
	msg = credPatterns.ReplaceAllString(msg, "[REDACTED]")
	return msg
}
