// Copyright 2026 enieuwy. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cobratree

import (
	"testing"

	"github.com/spf13/cobra"
)

// PATCH(glean facade-apply): the write-safety gate flags stay reachable for
// MUTATING commands (so applies work over MCP) and are stripped from read-only
// commands. Formatting/ops globals and hidden globals stay stripped everywhere.
var writeGatingGlobalFlagNames = []string{
	"allow-destructive",
	"continue-on-error",
	"dry-run",
	"max-changes",
	"max-failures",
	"yes",
}

var formattingGlobalFlagNames = []string{
	"agent",
	"compact",
	"csv",
	"data-source",
	"human-friendly",
	"idempotent",
	"ignore-missing",
	"json",
	"no-cache",
	"no-color",
	"no-input",
	"plain",
	"quiet",
	"rate-limit",
	"select",
	"timeout",
}

func allGlobalFlagNames() []string {
	out := append([]string{}, writeGatingGlobalFlagNames...)
	return append(out, formattingGlobalFlagNames...)
}

var stripHiddenGlobalFlagNames = []string{
	"config",
	"deliver",
	"group",
	"profile",
}

// stripNewRoot builds a root with every global persistent flag plus a child.
// readOnly toggles the mcp:read-only annotation that decides whether the child
// is treated as mutating (write-gating flags exposed) or read-only (stripped).
func stripNewRoot(readOnly bool) (*cobra.Command, *cobra.Command) {
	root := &cobra.Command{Use: "zotero"}
	for _, name := range allGlobalFlagNames() {
		switch name {
		case "max-changes", "max-failures":
			root.PersistentFlags().Int(name, 0, "global "+name)
		default:
			root.PersistentFlags().Bool(name, false, "global "+name)
		}
	}

	child := &cobra.Command{
		Use: "child",
		Run: func(*cobra.Command, []string) {},
	}
	if readOnly {
		child.Annotations = map[string]string{ReadOnlyAnnotation: "true"}
	}
	child.Flags().String("limit", "", "local limit")
	root.AddCommand(child)

	return root, child
}

func TestStripMutatingKeepsWriteGatingAndLocalDropsFormatting(t *testing.T) {
	_, child := stripNewRoot(false)
	allowed := safeFlagNames(child)

	if _, ok := allowed["limit"]; !ok {
		t.Fatal("safeFlagNames(mutating child) missing local flag limit")
	}
	for _, name := range writeGatingGlobalFlagNames {
		if _, ok := allowed[name]; !ok {
			t.Errorf("safeFlagNames(mutating child) dropped write-gating flag %q", name)
		}
	}
	for _, name := range formattingGlobalFlagNames {
		if _, ok := allowed[name]; ok {
			t.Errorf("safeFlagNames(mutating child) exposed formatting global %q", name)
		}
	}
}

func TestStripReadOnlyDropsAllInheritedGlobals(t *testing.T) {
	_, child := stripNewRoot(true)
	allowed := safeFlagNames(child)

	if _, ok := allowed["limit"]; !ok {
		t.Fatal("safeFlagNames(read-only child) missing local flag limit")
	}
	for _, name := range allGlobalFlagNames() {
		if _, ok := allowed[name]; ok {
			t.Errorf("safeFlagNames(read-only child) exposed inherited global flag %q", name)
		}
	}
}

func TestStripSafeToolOptionsCounts(t *testing.T) {
	_, mut := stripNewRoot(false)
	if got, want := len(safeToolOptionsForFlags(mut)), 1+len(writeGatingGlobalFlagNames); got != want {
		t.Fatalf("safeToolOptionsForFlags(mutating) length = %d, want %d", got, want)
	}
	_, ro := stripNewRoot(true)
	if got, want := len(safeToolOptionsForFlags(ro)), 1; got != want {
		t.Fatalf("safeToolOptionsForFlags(read-only) length = %d, want %d", got, want)
	}
}

func TestStripValidateAcceptsWriteGatingOnMutating(t *testing.T) {
	_, child := stripNewRoot(false)
	allowed := safeFlagNames(child)

	for _, name := range writeGatingGlobalFlagNames {
		name := name
		t.Run(name, func(t *testing.T) {
			if err := validateMirrorArguments(map[string]any{name: true}, allowed); err != nil {
				t.Fatalf("validateMirrorArguments rejected write-gating flag %q on mutating command: %v", name, err)
			}
		})
	}
}

func TestStripValidateRejectsWriteGatingOnReadOnly(t *testing.T) {
	_, child := stripNewRoot(true)
	allowed := safeFlagNames(child)

	for _, name := range writeGatingGlobalFlagNames {
		name := name
		t.Run(name, func(t *testing.T) {
			if err := validateMirrorArguments(map[string]any{name: true}, allowed); err == nil {
				t.Fatalf("validateMirrorArguments accepted write-gating flag %q on read-only command", name)
			}
		})
	}
}

func TestStripValidateRejectsFormattingGlobals(t *testing.T) {
	_, child := stripNewRoot(false)
	allowed := safeFlagNames(child)

	for _, name := range formattingGlobalFlagNames {
		name := name
		t.Run(name, func(t *testing.T) {
			if err := validateMirrorArguments(map[string]any{name: true}, allowed); err == nil {
				t.Fatalf("validateMirrorArguments accepted forged formatting global flag %q", name)
			}
		})
	}
}

func TestStripValidateRejectsRawFlagTokenInArgs(t *testing.T) {
	_, child := stripNewRoot(false)
	allowed := safeFlagNames(child)

	if err := validateMirrorArguments(map[string]any{"args": "--limit"}, allowed); err == nil {
		t.Fatal("validateMirrorArguments accepted raw flag token in args")
	}
}

func TestStripValidateAcceptsLocalFlag(t *testing.T) {
	_, child := stripNewRoot(false)
	allowed := safeFlagNames(child)

	if err := validateMirrorArguments(map[string]any{"limit": "5"}, allowed); err != nil {
		t.Fatalf("validateMirrorArguments rejected valid local flag: %v", err)
	}
}

func TestStripValidateRejectsUnregisteredHiddenGlobals(t *testing.T) {
	_, child := stripNewRoot(false)
	allowed := safeFlagNames(child)

	for _, name := range stripHiddenGlobalFlagNames {
		name := name
		t.Run(name, func(t *testing.T) {
			if err := validateMirrorArguments(map[string]any{name: true}, allowed); err == nil {
				t.Fatalf("validateMirrorArguments accepted unregistered hidden global flag %q", name)
			}
		})
	}
}
