// Copyright 2026 enieuwy. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cobratree

import (
	"testing"

	"github.com/spf13/cobra"
)

var stripGlobalFlagNames = []string{
	"agent",
	"allow-destructive",
	"compact",
	"continue-on-error",
	"csv",
	"data-source",
	"dry-run",
	"human-friendly",
	"idempotent",
	"ignore-missing",
	"json",
	"max-changes",
	"max-failures",
	"no-cache",
	"no-color",
	"no-input",
	"plain",
	"quiet",
	"rate-limit",
	"select",
	"timeout",
	"yes",
}

var stripHiddenGlobalFlagNames = []string{
	"config",
	"deliver",
	"group",
	"profile",
}

func stripNewRoot() (*cobra.Command, *cobra.Command) {
	root := &cobra.Command{Use: "zotero"}
	for _, name := range stripGlobalFlagNames {
		root.PersistentFlags().Bool(name, false, "global "+name)
	}

	child := &cobra.Command{
		Use: "child",
		Run: func(*cobra.Command, []string) {},
	}
	child.Flags().String("limit", "", "local limit")
	root.AddCommand(child)

	return root, child
}

func TestStripSafeFlagNamesDropsInheritedGlobalsKeepsLocal(t *testing.T) {
	_, child := stripNewRoot()
	allowed := safeFlagNames(child)

	if _, ok := allowed["limit"]; !ok {
		t.Fatal("safeFlagNames(child) missing local flag limit")
	}
	for _, name := range stripGlobalFlagNames {
		if _, ok := allowed[name]; ok {
			t.Errorf("safeFlagNames(child) exposed inherited global flag %q", name)
		}
	}
}

func TestStripSafeToolOptionsDropsInheritedGlobals(t *testing.T) {
	_, child := stripNewRoot()
	opts := safeToolOptionsForFlags(child)

	if got, want := len(opts), 1; got != want {
		t.Fatalf("safeToolOptionsForFlags(child) length = %d, want %d", got, want)
	}
}

func TestStripValidateRejectsForgedInheritedGlobals(t *testing.T) {
	_, child := stripNewRoot()
	allowed := safeFlagNames(child)

	for _, name := range stripGlobalFlagNames {
		name := name
		t.Run(name, func(t *testing.T) {
			if err := validateMirrorArguments(map[string]any{name: true}, allowed); err == nil {
				t.Fatalf("validateMirrorArguments accepted forged inherited global flag %q", name)
			}
		})
	}
}

func TestStripValidateRejectsRawFlagTokenInArgs(t *testing.T) {
	_, child := stripNewRoot()
	allowed := safeFlagNames(child)

	if err := validateMirrorArguments(map[string]any{"args": "--limit"}, allowed); err == nil {
		t.Fatal("validateMirrorArguments accepted raw flag token in args")
	}
}

func TestStripValidateAcceptsLocalFlag(t *testing.T) {
	_, child := stripNewRoot()
	allowed := safeFlagNames(child)

	if err := validateMirrorArguments(map[string]any{"limit": "5"}, allowed); err != nil {
		t.Fatalf("validateMirrorArguments rejected valid local flag: %v", err)
	}
}

func TestStripValidateRejectsUnregisteredHiddenGlobals(t *testing.T) {
	_, child := stripNewRoot()
	allowed := safeFlagNames(child)

	for _, name := range stripHiddenGlobalFlagNames {
		name := name
		t.Run(name, func(t *testing.T) {
			if err := validateMirrorArguments(map[string]any{name: true}, allowed); err == nil {
				t.Fatalf("validateMirrorArguments accepted unregistered hidden global flag %q", name)
			}
		})
	}
}
