// Copyright 2026 OrgMentem. Licensed under MIT. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cobratree

import (
	"bytes"
	"context"
	"fmt"
	"sort"
	"strconv"
	"strings"
	"sync"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"github.com/spf13/cobra"
)

var mirroredCommandMu sync.Mutex

// inProcessHandler runs a mirrored Cobra command in-process via the shared
// runMirroredInProcess core. PATCH(glean c4ke): replaces the previous shell-out
// to a companion zotio binary, so the MCP server works without that
// binary on PATH.
func inProcessHandler(rootFactory func() *cobra.Command, commandPath []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		return runMirroredInProcess(ctx, rootFactory, commandPath, req.GetArguments()), nil
	}
}

// runMirroredInProcess builds a fresh command tree (cobra.Command state is
// single-use) and runs the mirrored command in-process. PATCH(glean f-plain):
// inject --agent (when the root defines it) so mirror tools always return
// structured, non-interactive output regardless of which flags the MCP schema
// exposes. This is the out-of-band mechanism that lets the schema drop
// --agent/--json and the other global formatting/confirmation flags. Shared by
// the command mirror (inProcessHandler) and the orchestration facade (command_run).
func runMirroredInProcess(ctx context.Context, rootFactory func() *cobra.Command, commandPath []string, args map[string]any) *mcplib.CallToolResult {
	// PATCH(glean mcp-active-group-race): CLI package state (notably the
	// group-selected local DB/API prefix) is still process-global. Serialize the
	// in-process mirror so concurrent HTTP MCP requests cannot cross-contaminate
	// library scope while commands run.
	mirroredCommandMu.Lock()
	defer mirroredCommandMu.Unlock()
	root := rootFactory()
	if root == nil {
		return mcplib.NewToolResultError("failed to build command tree")
	}
	finalArgs := append([]string{}, commandPath...)
	if root.PersistentFlags().Lookup("agent") != nil || root.Flags().Lookup("agent") != nil {
		finalArgs = append(finalArgs, "--agent")
	}
	finalArgs = append(finalArgs, cliArgsFromMCP(args)...)
	if raw, _ := args["args"].(string); strings.TrimSpace(raw) != "" {
		finalArgs = append(finalArgs, splitShellArgs(raw)...)
	}
	var buf bytes.Buffer
	root.SetOut(&buf)
	root.SetErr(&buf)
	root.SetArgs(finalArgs)
	if err := root.ExecuteContext(ctx); err != nil {
		return mcplib.NewToolResultError(buf.String() + "\n" + err.Error())
	}
	return mcplib.NewToolResultText(buf.String())
}

func cliArgsFromMCP(args map[string]any) []string {
	keys := make([]string, 0, len(args))
	for k := range args {
		if k != "args" {
			keys = append(keys, k)
		}
	}
	sort.Strings(keys)

	var out []string
	for _, k := range keys {
		v := args[k]
		switch tv := v.(type) {
		case bool:
			if tv {
				out = append(out, "--"+k)
			}
		case float64:
			out = append(out, "--"+k, strconv.FormatFloat(tv, 'f', -1, 64))
		case string:
			if tv != "" {
				out = append(out, "--"+k, tv)
			}
		case []any:
			if len(tv) > 0 {
				parts := make([]string, 0, len(tv))
				for _, item := range tv {
					parts = append(parts, fmt.Sprintf("%v", item))
				}
				out = append(out, "--"+k, strings.Join(parts, ","))
			}
		default:
			if v != nil {
				out = append(out, "--"+k, fmt.Sprintf("%v", v))
			}
		}
	}
	return out
}

// splitShellArgs whitespace-splits with double-quoted-token preservation.
func splitShellArgs(s string) []string {
	var tokens []string
	var cur []rune
	inQuote := false
	for _, r := range s {
		switch {
		case r == '"':
			inQuote = !inQuote
		case (r == ' ' || r == '\t') && !inQuote:
			if len(cur) > 0 {
				tokens = append(tokens, string(cur))
				cur = cur[:0]
			}
		default:
			cur = append(cur, r)
		}
	}
	if len(cur) > 0 {
		tokens = append(tokens, string(cur))
	}
	return tokens
}
